import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Navigation
    'nav.features': 'Características',
    'nav.success_cases': 'Casos de Éxito',
    'nav.login': 'Iniciar Sesión',
    'nav.start_free': 'Empezar Gratis',
    'nav.navigation': 'Navegación',
    'nav.logout': 'Cerrar Sesión',
    
    // Hero Section
    'hero.badge': 'IA · Mentoría · Crecimiento Diario',
    'hero.title_part1': 'no te entrena para un curso.',
    'hero.title_part2': 'Te transforma para siempre.',
    'hero.description': 'Tu mentora de inteligencia artificial que impulsa la evolución y el crecimiento diario de equipos en el sector de TI. Una experiencia retadora, emocionalmente inteligente y visionaria.',
    'hero.start_evolution': 'Comenzar tu Evolución',
    'hero.watch_demo': 'Ver Demo',
    
    // Features Section
    'features.title': '¿Cómo funciona',
    'features.description': 'Una plataforma completa que combina inteligencia artificial, gamificación y mentoría personalizada para acelerar el crecimiento de tu equipo.',
    'features.dashboard.title': 'Dashboard Personalizado',
    'features.dashboard.description': 'Visualiza métricas de progreso, sesiones completadas y racha de días activos en tiempo real.',
    'features.workplan.title': 'Plan de Trabajo Visual',
    'features.workplan.description': 'Rutas de aprendizaje personalizadas con módulos y objetivos claros en formato interactivo.',
    'features.achievements.title': 'Sistema de Logros',
    'features.achievements.description': 'Insignias, XP y leaderboards que motivan la constancia y celebran cada hito alcanzado.',
    'features.calendar.title': 'Calendario Inteligente',
    'features.calendar.description': 'Sesiones de mentoría sincronizadas con Google Calendar y Outlook para una organización perfecta.',
    
    // Benefits Section
    'benefits.title': 'Más que una herramienta, un compañero de crecimiento',
    'benefits.description': 'no es solo tecnología. Es una experiencia diseñada para crear conexiones humanas auténticas mientras potencia el desarrollo profesional de cada miembro de tu equipo.',
    'benefits.mentoring': 'Mentoría personalizada basada en IA avanzada',
    'benefits.integration': 'Integración perfecta con herramientas existentes',
    'benefits.automation': 'Automatización inteligente de flujos de trabajo',
    'benefits.metrics': 'Métricas claras de progreso y ROI',
    'benefits.humanity.title': 'Humanidad Aumentada',
    'benefits.humanity.description': 'Tecnología que potencia la conexión humana, no que la reemplaza. Cada interacción está diseñada para ser auténtica, retadora y transformadora.',
    
    // Testimonials
    'testimonials.title': 'Lo que dicen nuestros usuarios',
    'testimonials.subtitle': 'Líderes de TI que ya están transformando sus equipos con',
    'testimonials.carlos.content': 'La plataforma ha revolucionado cómo desarrollamos talento en nuestro equipo. Los resultados son medibles y el engagement ha aumentado un 300%.',
    'testimonials.ana.content': 'La gamificación realmente funciona. Nuestros desarrolladores están más motivados y las habilidades blandas han mejorado significativamente.',
    'testimonials.roberto.content': 'La automatización de la plataforma nos ahorra 10 horas semanales en gestión de equipo, permitiéndonos enfocarnos en lo que realmente importa.',
    
    // CTA Section
    'cta.title': '¿Listo para transformar tu equipo?',
    'cta.description': '�snete a cientos de líderes de TI que ya están viendo resultados reales. Comienza tu prueba gratuita hoy y descubre el potencial de tu equipo.',
    'cta.start_trial': 'Iniciar Prueba Gratuita',
    'cta.schedule_demo': 'Agendar Demo',
    
    // Footer
    'footer.copyright': 'Transformando el futuro del aprendizaje en TI.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Cargando dashboard...',
    'dashboard.home': 'Dashboard',
    'dashboard.org.title': 'Dashboard de Mi Organización',
    'dashboard.org.description': 'Vista de tu equipo y progreso organizacional',
    // Dashboard User
    'dashboard.user.title': 'My Dashboard',
    'dashboard.user.greeting': 'Hello',
    'dashboard.user.user': 'User',
    'dashboard.user.description': 'Here is your personal coaching progress',
    'dashboard.user.radar_title': '360° Competency Assessment',
    'dashboard.user.radar_description': 'Comparison between your self-assessment and your coach\'s assessment',
    'dashboard.user.my_sessions': 'My Sessions',
    'dashboard.user.upcoming': 'Upcoming',
    'dashboard.user.consistency': 'My Consistency',
    'dashboard.user.wellbeing': 'My Wellbeing',
    'dashboard.user.sessions_completed': 'Sessions completed',
    'dashboard.user.sessions_scheduled': 'Scheduled sessions',
    'dashboard.user.attendance_rate': 'Attendance rate',
    'dashboard.user.average_mood': 'Average mood',
    'dashboard.user.monthly_progress': 'My Monthly Progress',
    'dashboard.user.monthly_description': 'Your evolution in recent months',
    'dashboard.user.sessions_status': 'My Sessions',
    'dashboard.user.status_description': 'Status of your sessions',
    'dashboard.user.weekly_activity': 'My Weekly Activity',
    'dashboard.user.weekly_description': 'Tus sesiones en la última semana',
    'dashboard.user.clarity': 'Claridad (C)',
    'dashboard.user.structure': 'Estructura (E)',  
    'dashboard.user.emotional_alignment': 'Alineación Emocional (A)',
    'dashboard.user.action_influence': 'Acción e Influencia (I)',
    'dashboard.user.my_evaluation': 'Mi Evaluación',
    'dashboard.user.coach_evaluation': 'Evaluación Coach',
    'dashboard.charts.monthly_performance': 'Rendimiento Mensual del Equipo',
    'dashboard.charts.monthly_description': 'Progreso de tu organización por mes',
    'dashboard.charts.team_sessions': 'Sesiones del Equipo',
    'dashboard.charts.completed': 'Completadas',
    'dashboard.charts.team_status': 'Estado del Equipo',
    'dashboard.charts.status_description': 'Distribución de sesiones',
    'dashboard.charts.weekly_activity': 'Actividad Semanal del Equipo',
    'dashboard.charts.weekly_description': 'Sesiones diarias de tu organización',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.coach': 'Coach',
    'nav.roleplay': 'Sala de entrenamiento',
    'nav.first_interview': 'Mi Primera Entrevista',
    'nav.interview_history': 'Historial de Entrevistas',
    'nav.demo': 'Demo',
    'nav.demo_training': 'Demo Entrenamiento',
    'nav.roleplay_progress': 'Mi Progreso',
    'nav.learning_path': 'Ruta de Aprendizaje',
    'nav.team_learning_progress': 'Progreso del Equipo',
    'nav.sessions': 'Historial',
    'nav.analytics': 'Analytics',
    'nav.organizations': 'Organizaciones',
    'nav.users': 'Usuarios',
    'nav.reports': 'Reports',
    'nav.trends': 'Trends',
    'nav.plans': 'Planes',
    'nav.documents': 'Documentos',
    'nav.settings': 'Ajustes',
    'nav.my_team': 'Mi Equipo',
    'nav.plan': 'Plan',
    'nav.achievements': 'Logros',
    'dashboard.analytics': 'Analytics',
    'dashboard.reports': 'Reports',
    'dashboard.trends': 'Trends',
    'dashboard.users': 'Usuarios',
    'dashboard.plans': 'Planes',
    'dashboard.settings': 'Settings',
    'dashboard.team.title': 'Mi Equipo',
    'dashboard.team.description': 'Gestiona y administra los miembros de tu equipo',
    'dashboard.team.upload_csv': 'Cargar Usuarios desde CSV',
    'dashboard.team.upload_description': 'Importa múltiples usuarios a tu equipo utilizando un archivo CSV',
    'dashboard.team.download_template': 'Descargar Plantilla',
    'dashboard.team.processing': 'Procesando archivo CSV...',
    'dashboard.team.results_title': 'Resultados de la Carga',
    'dashboard.team.successful': 'Exitosos',
    'dashboard.team.failed': 'Fallidos',
    'dashboard.team.total': 'Total',
    'dashboard.team.errors': 'Errores',
    'dashboard.team.format_required': 'Formato requerido',
    'dashboard.team.members': 'Miembros del Equipo',
    'dashboard.team.members_description': 'Lista de todos los miembros de tu equipo y su estado actual',
    'dashboard.team.name': 'Nombre',
    'dashboard.team.email': 'Email',
    'dashboard.team.role': 'Rol',
    'dashboard.team.status': 'Estado',
    'dashboard.team.join_date': 'Fecha de Ingreso',
    'dashboard.team.status_active': 'Activo',
    'dashboard.team.status_pending': 'Pendiente',
    'dashboard.team.status_suspended': 'Suspendido',
    'dashboard.team.upload_success': 'Carga completada',
    'dashboard.team.upload_error': 'Error en la carga',
    'dashboard.team.template_downloaded': 'Plantilla descargada',
    'dashboard.team.csv_error': 'Por favor selecciona un archivo CSV válido',

    // Coach
    'coach.title': 'Coach IA',
    'coach.subtitle': 'Tu mentor personal para crecimiento profesional',
    'coach.ai_coach': 'Coach de Inteligencia Artificial',
    'coach.description': 'Conversa con tu coach personal powered by AI para obtener mentoría personalizada',
    'coach.status.ready': 'Listo para conversar',
    'coach.status.connecting': 'Conectando...',
    'coach.status.listening': 'Escuchando...',
    'coach.status.thinking': 'Procesando...',
    'coach.status.speaking': 'Respondiendo...',
    'coach.start_listening': 'Iniciar Conversación',
    'coach.stop_listening': 'Detener',
    'coach.mute': 'Silenciar',
    'coach.unmute': 'Activar Audio',
    'coach.instructions': 'Escribe tu consulta y obtén coaching personalizado en tiempo real',
    'coach.error.no_api_key': 'Modo demo - La integración completa de voz requiere configuración',
    'coach.new_conversation': 'Nueva Conversación',
    'coach.voice_mode': 'Modo Voz (Próximamente)',
    'coach.placeholder': 'Escribe tu consulta de coaching...',
    'coach.thinking': 'Tu coach está pensando...',
    'coach.specialties': 'Tu coach inteligente está listo para ayudarte con liderazgo, productividad y desarrollo profesional',

    // AI Resources
    'nav.ai_resources': 'Recursos Educativos IA',
    'ai_resources.title': 'Recursos Educativos IA',
    'ai_resources.description': 'Recursos de inteligencia artificial para capacitación',
    'ai_resources.open_resource': 'Abrir Recurso',
    'ai_resources.add_resource': 'Agregar Recurso',
    'ai_resources.add_title': 'Nuevo Recurso Educativo',
    'ai_resources.form.title': 'Título',
    'ai_resources.form.title_placeholder': 'Nombre del recurso',
    'ai_resources.form.description': 'Descripción',
    'ai_resources.form.description_placeholder': 'Breve descripción del recurso',
    'ai_resources.form.url': 'URL del Recurso',
    'ai_resources.form.url_placeholder': 'https://ejemplo.com',
    'ai_resources.form.icon': 'Icono',
    'ai_resources.form.color': 'Color',
    'ai_resources.form.submit': 'Guardar Recurso',
    'ai_resources.form.cancel': 'Cancelar',
    'ai_resources.success': 'Recurso agregado correctamente',
    'ai_resources.error': 'Error al agregar recurso',
    'ai_resources.loading': 'Cargando recursos...',
    'ai_resources.empty': 'No hay recursos disponibles',

    // Learning Content (Biblioteca)
    'nav.learning_content': 'Biblioteca',
    'nav.desc.learning_content': 'Videos, podcasts y materiales de estudio',
    'learning_content.title': 'Biblioteca de Contenido',
    'learning_content.description': 'Explora videos, podcasts, PDFs y artículos para seguir aprendiendo',
    'learning_content.add': 'Agregar Contenido',
    'learning_content.add_title': 'Nuevo Contenido',
    'learning_content.loading': 'Cargando contenido...',
    'learning_content.empty': 'No hay contenido disponible aún',
    'learning_content.error': 'Error al cargar contenido',
    'learning_content.open': 'Abrir recurso',
    'learning_content.all': 'Todos',
    'learning_content.videos': 'Videos',
    'learning_content.podcasts': 'Podcasts',
    'learning_content.pdfs': 'PDFs',
    'learning_content.articles': 'Artículos',
    'learning_content.form.title': 'Título',
    'learning_content.form.description': 'Descripción',
    'learning_content.form.url': 'URL del recurso',
    'learning_content.form.type': 'Tipo de contenido',
    'learning_content.form.thumbnail': 'URL de portada (opcional)',
    'learning_content.form.duration': 'Duración (opcional)',
    'learning_content.form.cancel': 'Cancelar',
    'learning_content.form.submit': 'Crear',
    'learning_content.success': 'Contenido creado exitosamente',
    'learning_content.delete_success': 'Contenido eliminado',
    'learning_content.type.video': 'Video',
    'learning_content.type.podcast': 'Podcast',
    'learning_content.type.pdf': 'PDF',
    'learning_content.type.article': 'Artículo',

    // Avatar Showcase
    'nav.avatar_showcase': 'Comparativa Avatares',
    'avatar_showcase.title': 'Comparativa de Avatares Voxel',
    'avatar_showcase.description': 'Compara diferentes enfoques para renderizar avatares 3D estilo voxel',

    // Navigation - Additional items
    'nav.avatar': 'Mi Avatar',
    'nav.stats': 'Mis Estadísticas',
    'nav.agent_config': 'Configuración Agentes',
    'nav.welcome': 'Hola',
    'nav.welcome_subtitle': '¿Qué quieres hacer hoy?',

    // Navigation - Card descriptions
    'nav.desc.dashboard': 'Tu página de inicio',
    'nav.desc.avatar': 'Personaliza tu avatar 3D',
    'nav.desc.stats': 'Métricas y gráficos de tu progreso',
    'nav.desc.first_interview': 'Entrevista inicial estructurada',
    'nav.desc.roleplay': 'Practica escenarios con IA',
    'nav.desc.learning_path': 'Tu camino de desarrollo',
    'nav.desc.progress': 'Ve tu avance y métricas',
    'nav.desc.sessions': 'Historial de sesiones',
    'nav.desc.team_progress': 'Progreso de tu equipo',
    'nav.desc.my_team': 'Gestiona tu equipo',
    'nav.desc.plans': 'Planes de suscripción',
    'nav.desc.documents': 'Documentos del equipo',
    'nav.desc.settings': 'Configuración de cuenta',
    'nav.desc.coach': 'Conversación con tu coach IA',
    'nav.desc.agent_config': 'Configura perfiles y escenarios',
    'nav.desc.ai_resources': 'Recursos educativos de IA',
    'nav.desc.avatar_showcase': 'Galería de avatares',
    'nav.desc.demo': 'Prueba la plataforma',
    'nav.desc.demo_training': 'Entrenamiento de demostración',
    'nav.desc.analytics': 'Métricas de la plataforma',
    'nav.desc.organizations': 'Gestiona organizaciones',
    'nav.desc.users': 'Administra usuarios',
    'nav.desc.reports': 'Reportes detallados',
    'nav.desc.trends': 'Tendencias y patrones',
    'nav.desc.tech_week': 'Evento especial Tech Week',
    'nav.desc.interview_history': 'Historial de entrevistas',
    'nav.desc.hero_journey': 'Visualiza tu camino como una montaña',
    'nav.hero_journey': "Hero's Journey",
    'nav.omi_conversations': 'Mis Conversaciones',
    'nav.desc.omi_conversations': 'Grabaciones y análisis de Omi',
    'nav.web_recorder': 'Grabadora Web',
    'nav.desc.web_recorder': 'Graba conversaciones desde el navegador',

    // Web Recorder
    'recorder.speaker_you': 'Tú',
    'recorder.participants_detected': 'Participantes Detectados',
    'recorder.participant': 'Participante',
    'recorder.words': 'palabras',
    'recorder.guard_title': 'Grabación en Curso',
    'recorder.guard_description': 'Tienes una grabación activa. ¿Qué deseas hacer?',
    'recorder.guard_cancel': 'Continuar Grabando',
    'recorder.guard_confirm': 'Guardar y Salir',
    'recorder.guard_saving': 'Guardando...',

    // Navigation - Section headers
    'nav.section.profile': 'Mi Perfil',
    'nav.section.profile_desc': 'Tu información personal',
    'nav.section.practice': 'Práctica',
    'nav.section.practice_desc': 'Mejora tus habilidades de comunicación',
    'nav.section.progress': 'Mi Progreso',
    'nav.section.progress_desc': 'Revisa tu avance y resultados',
    'nav.section.team': 'Mi Equipo',
    'nav.section.team_desc': 'Gestión y seguimiento del equipo',
    'nav.section.config': 'Configuración',
    'nav.section.config_desc': 'Ajustes y documentos',
    'nav.section.admin': 'Administración',
    'nav.section.admin_desc': 'Herramientas de administrador',

    // Roles
    'roles.admin': 'Administrador Global',
    'roles.manager': 'Administrador',
    'roles.user': 'Usuario',
    'roles.default_user': 'Usuario',

    // Omi Conversations
    'omi.page_description': 'Revisa tus conversaciones grabadas y su análisis',
    'omi.error_loading': 'Error al cargar las conversaciones',
    'omi.no_conversations': 'No hay conversaciones',
    'omi.no_conversations_desc': 'Tus conversaciones grabadas con Omi aparecerán aquí',
    'omi.communication_analysis': 'Análisis de Comunicación',
    'omi.overall_score': 'Puntuación General',
    'omi.clarity': 'Claridad',
    'omi.engagement': 'Engagement',
    'omi.structure': 'Estructura',
    'omi.strengths': 'Fortalezas',
    'omi.areas_to_improve': 'Áreas de Mejora',
    'omi.insights': 'Insights de Comunicación',
    'omi.objections': 'Manejo de Objeciones',
    'omi.calls_to_action': 'Llamados a Acción',
    'omi.action_items': 'Acciones Pendientes',
    'omi.events': 'Eventos',
    'omi.transcript': 'Transcripción',
    'omi.no_transcript': 'No hay transcripción disponible',
    // Omi Radiografía (análisis extendido)
    'omi.radiografia': 'Radiografía de Comunicación',
    'omi.muletillas': 'Muletillas',
    'omi.muletillas_detected': 'Muletillas Detectadas',
    'omi.muletillas_frequency': 'Frecuencia de muletillas',
    'omi.talk_ratio': 'Ratio de Habla',
    'omi.balanced': 'Equilibrado',
    'omi.unbalanced': 'Desbalanceado',
    'omi.words_user': 'Tus Palabras',
    'omi.you': 'Tú',
    'omi.others': 'Otros',
    'omi.questions': 'Preguntas',
    'omi.your_questions': 'Tus Preguntas',
    'omi.questions_received': 'Preguntas Recibidas',
    'omi.no_questions': 'Sin preguntas registradas',
    'omi.topics': 'Temas Tratados',
    'omi.your_commitments': 'Tus Compromisos',
    'omi.with_date': 'con fecha',
    'omi.without_date': 'sin fecha',
    'omi.open_topics': 'Temas Sin Cerrar',
    'omi.reason': 'Razón',
    'omi.delete_conversation': '¿Eliminar conversación?',
    'omi.delete_conversation_description': 'Esta acción marcará la conversación como eliminada.',
    'omi.reanalyze': 'Reanalizar',
    'omi.conversation_id': 'ID',
    'omi.copy_id': 'Copiar ID',
    'omi.id_copied': 'ID copiado',
    // Omi Analysis Sections
    'omi.analysis_title': 'Análisis de Tu Comunicación',
    'omi.minutes': 'minutos',
    'omi.words_analyzed': 'palabras analizadas',
    'omi.summary_section': 'Resumen',
    'omi.quick_radiography': 'Radiografía Rápida',
    'omi.communication_metrics': 'Métricas de Comunicación',
    'omi.muletillas_section': 'Muletillas Detectadas',
    'omi.questions_section': 'Análisis de Preguntas',
    'omi.topics_section': 'Temas Tratados',
    'omi.commitments_section': 'Tus Compromisos',
    'omi.pending_section': 'Temas Pendientes',
    'omi.strengths_section': 'Fortalezas a Mantener',
    'omi.areas_section': 'Áreas de Mejora',
    'omi.transcript_section': 'Transcripción',
    'omi.of_10_points': 'de 10 puntos',
    'omi.score_excellent': 'Excelente',
    'omi.score_good': 'Buen trabajo',
    'omi.score_developing': 'En desarrollo',
    'omi.no_feedback_available': 'No hay retroalimentación disponible para esta conversación.',
    'omi.level_excellent': 'Excelente',
    'omi.level_good': 'Bueno',
    'omi.level_developing': 'En desarrollo',
    'omi.level_needs_work': 'Necesita trabajo',
    'omi.participant': 'Participante',
    'omi.new_recording': 'Nueva Grabación',
    // KPI Grid translations
    'omi.no_muletillas': 'Sin muletillas',
    'omi.balanced_conversation': 'Conversación equilibrada',
    'omi.you_talk_more': 'Hablas más que otros',
    'omi.others_talk_more': 'Otros hablan más',
    'omi.no_questions_data': 'Sin datos de preguntas',
    'omi.words_others': 'Palabras Otros',
    'omi.total': 'Total',
    'omi.no_topics': 'Sin temas identificados',
    'omi.commitments': 'Compromisos',
    'omi.no_commitments': 'Sin compromisos',
    'omi.all_closed': 'Todos los temas cerrados',
    // Score descriptions
    'omi.clarity_desc_high': 'Comunicación clara y precisa',
    'omi.clarity_desc_medium': 'Algunas áreas pueden mejorar',
    'omi.clarity_desc_low': 'Muletillas dificultan comprensión',
    'omi.structure_desc_high': 'Ideas bien organizadas',
    'omi.structure_desc_medium': 'Estructura mejorable',
    'omi.structure_desc_low': 'Ideas desorganizadas',
    'omi.empatia': 'Empatía',
    'omi.vocabulario': 'Vocabulario',
    'omi.objetivo': 'Objetivo',
    'omi.empatia_desc_high': 'Excelente escucha y conexión',
    'omi.empatia_desc_medium': 'Escucha activa mejorable',
    'omi.empatia_desc_low': 'Poco enfoque en escuchar a otros',
    'omi.vocabulario_desc_high': 'Vocabulario rico y apropiado',
    'omi.vocabulario_desc_medium': 'Vocabulario adecuado',
    'omi.vocabulario_desc_low': 'Vocabulario limitado o coloquial',
    'omi.objetivo_desc_high': 'Conversación muy enfocada con acciones claras',
    'omi.objetivo_desc_medium': 'Algunos temas sin cierre concreto',
    'omi.objetivo_desc_low': 'Sin objetivos claros ni compromisos',
    'omi.conversation_not_found': 'Conversación no encontrada',
    'omi.conversation_not_found_desc': 'La conversación que buscas no existe o no tienes acceso a ella.',
    'omi.back_to_conversations': 'Volver a conversaciones',
    'common.back': 'Volver',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.processing': 'Procesando...',

    // Dashboard - Omi Stats Section
    'dashboard.user.omi_section': 'Mis Conversaciones Omi',
    'dashboard.user.omi_description': 'Análisis de tus conversaciones grabadas',
    'dashboard.user.omi_avg_scores': 'Puntuaciones Promedio',
    'dashboard.user.omi_evolution': 'Evolución de Puntuación',
    'dashboard.user.omi_total_conversations': 'Conversaciones',
    'dashboard.user.omi_avg_score': 'Puntuación Promedio',
    'dashboard.user.omi_total_time': 'Tiempo Total',
    'dashboard.user.omi_no_data': 'Sin datos de conversaciones',
    'dashboard.user.omi_no_data_desc': 'Graba conversaciones con Omi para ver tu análisis aquí',
    'dashboard.user.omi_overall': 'General',

    // Meeting Analysis
    'nav.meeting_analysis': 'Análisis de Reunión',
    'nav.desc.meeting_analysis': 'Dashboard de análisis de comunicación en reuniones',

    // SVG Converter
    'nav.svg_converter': 'Convertidor SVG',
    'nav.desc.svg_converter': 'Convierte imágenes a SVG y gestiona assets',

    // Recorder Logs
    'nav.recorder_logs': 'Logs de Grabación',
    'nav.desc.recorder_logs': 'Debug logs de sesiones del web recorder',
    'svg_converter.title': 'Convertidor SVG',
    'svg_converter.description': 'Convierte imágenes a vectores y gestiona tu galería de assets',
    'svg_converter.tab_convert': 'Convertir',
    'svg_converter.tab_gallery': 'Galería',
    'svg_converter.drag_drop_or_click': 'Arrastra una imagen o haz clic para seleccionar',
    'svg_converter.drop_here': 'Suelta la imagen aquí',
    'svg_converter.supported_formats': 'Formatos soportados: JPG, PNG, WebP',
    'svg_converter.max_file_size': 'Tamaño máximo: 5MB',
    'svg_converter.error_invalid_format': 'Formato de archivo no válido. Usa JPG, PNG o WebP.',
    'svg_converter.error_file_too_large': 'El archivo es demasiado grande. Máximo 5MB.',
    'svg_converter.settings_title': 'Configuración',
    'svg_converter.preset_label': 'Tipo de imagen',
    'svg_converter.preset_photo': 'Fotografía',
    'svg_converter.preset_logo': 'Logo',
    'svg_converter.preset_illustration': 'Ilustración',
    'svg_converter.preset_line_art': 'Line Art',
    'svg_converter.color_count_label': 'Cantidad de colores',
    'svg_converter.color_count_hint': 'Menos colores = archivo más pequeño',
    'svg_converter.original': 'Original',
    'svg_converter.converted': 'SVG Convertido',
    'svg_converter.converting': 'Convirtiendo...',
    'svg_converter.no_preview': 'Sin vista previa',
    'svg_converter.error_conversion_failed': 'Error al convertir la imagen',
    'svg_converter.warning_large_svg': 'El SVG generado es grande ({size} KB). Considera reducir los colores.',
    'svg_converter.reset': 'Nueva imagen',
    'svg_converter.download': 'Descargar',
    'svg_converter.save_to_gallery': 'Guardar en galería',
    'svg_converter.save_dialog_title': 'Guardar asset',
    'svg_converter.save_dialog_description': 'Añade información para guardar este SVG en la galería',
    'svg_converter.field_name': 'Nombre',
    'svg_converter.field_name_placeholder': 'Nombre del asset',
    'svg_converter.field_description': 'Descripción',
    'svg_converter.field_description_placeholder': 'Descripción opcional',
    'svg_converter.field_category': 'Categoría',
    'svg_converter.field_tags': 'Etiquetas',
    'svg_converter.field_tags_placeholder': 'logo, icono, banner',
    'svg_converter.field_tags_hint': 'Separadas por coma',
    'svg_converter.category_general': 'General',
    'svg_converter.category_icons': 'Iconos',
    'svg_converter.category_illustrations': 'Ilustraciones',
    'svg_converter.category_logos': 'Logos',
    'svg_converter.category_backgrounds': 'Fondos',
    'svg_converter.category_patterns': 'Patrones',
    'svg_converter.save': 'Guardar',
    'svg_converter.success': 'Éxito',
    'svg_converter.error': 'Error',
    'svg_converter.error_name_required': 'El nombre es requerido',
    'svg_converter.error_save_failed': 'Error al guardar el asset',
    'svg_converter.asset_saved': 'Asset guardado correctamente',
    'svg_converter.search_placeholder': 'Buscar assets...',
    'svg_converter.all_categories': 'Todas las categorías',
    'svg_converter.loading': 'Cargando...',
    'svg_converter.error_loading': 'Error al cargar los assets',
    'svg_converter.no_assets': 'No hay assets',
    'svg_converter.no_assets_hint': 'Convierte una imagen para crear tu primer asset',
    'svg_converter.inactive': 'Inactivo',
    'svg_converter.active': 'Activo',
    'svg_converter.asset_details': 'Detalles del asset',
    'svg_converter.asset_details_description': 'Información y acciones del asset',
    'svg_converter.edit_asset': 'Editar asset',
    'svg_converter.edit_asset_description': 'Modifica la información del asset',
    'svg_converter.edit': 'Editar',
    'svg_converter.delete': 'Eliminar',
    'svg_converter.copy_svg': 'Copiar SVG',
    'svg_converter.copied': 'Copiado',
    'svg_converter.error_copy_failed': 'Error al copiar',
    'svg_converter.activate': 'Activar',
    'svg_converter.deactivate': 'Desactivar',
    'svg_converter.asset_updated': 'Asset actualizado',
    'svg_converter.asset_activated': 'Asset activado',
    'svg_converter.asset_deactivated': 'Asset desactivado',
    'svg_converter.error_update_failed': 'Error al actualizar',
    'svg_converter.delete_confirm_title': '¿Eliminar asset?',
    'svg_converter.delete_confirm_description': 'Esta acción desactivará el asset. Podrás reactivarlo más tarde.',
    'svg_converter.asset_deleted': 'Asset eliminado',
    'svg_converter.error_delete_failed': 'Error al eliminar',

    // Desktop App Download
    'nav.desktop_app': 'App de Escritorio',
    'nav.desc.desktop_app': 'Descarga Maity para tu computadora',
    'download.title': 'App de Escritorio',
    'download.subtitle': 'Descarga Maity para tu computadora',
    'download.description': 'Instala la aplicación de escritorio para una experiencia optimizada',
    'download.version': 'Versión',
    'download.download_for': 'Descargar para',
    'download.recommended': 'Recomendado para ti',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.other_platforms': 'Otras plataformas',
    'download.features_title': 'Características',
    'download.feature_offline': 'Acceso offline',
    'download.feature_notifications': 'Notificaciones nativas',
    'download.feature_performance': 'Mejor rendimiento',
    'download.feature_auto_updates': 'Actualizaciones automáticas',
    'download.requirements_windows': 'Windows 10 o superior (64-bit)',
    'download.requirements_macos': 'macOS 10.15 o superior',
    'download.coming_soon': 'Proximamente',
    'download.windows_available': 'Mientras tanto, la version de Windows ya esta disponible:',
    'download.view_all_releases': 'Ver todas las versiones',
    'download.loading': 'Cargando información de descarga...',
    'download.error': 'Error al cargar',
    'download.error_description': 'No se pudo obtener la información de descarga. Intenta de nuevo más tarde.',
    'download.retry': 'Reintentar',

    // Skills Arena
    'nav.skills_arena': 'Arena de Habilidades',
    'nav.desc.skills_arena': 'Tests y juegos para desarrollar soft skills',
    'skills_arena.title': 'Arena de Habilidades',
    'skills_arena.subtitle': '¡Bienvenido, {name}! Desafía tus habilidades.',
    'skills_arena.featured': 'DESTACADO',
    'skills_arena.start': 'Comenzar',
    'skills_arena.continue': 'Continuar',
    'skills_arena.completed': 'Completado',
    'skills_arena.locked': 'Bloqueado',
    'skills_arena.progress': 'Progreso',
    'skills_arena.questions': 'preguntas',
    'skills_arena.all_tests': 'Todos los Tests',
    'skills_arena.available': 'disponibles',
    'skills_arena.tests_label': 'Tests',
    'skills_arena.streak_label': 'Días Racha',
    'skills_arena.best_score': 'Mejor puntaje',
    'skills_arena.no_tests_in_category': 'No hay tests en esta categoría',
    'skills_arena.badges': 'Insignias',
    // Skills Arena Resources
    'skills_arena.resources_title': 'Recursos Educativos',
    'skills_arena.resources_description': 'Herramientas y materiales para potenciar tu desarrollo',
    'skills_arena.resources_count': 'recursos',
    'skills_arena.resource_type': 'Recurso',
    'skills_arena.open_resource': 'Abrir recurso',
    // Skills Arena Categories
    'skills_arena.category.all': 'Todos',
    'skills_arena.category.self_knowledge': 'Autoconocimiento',
    'skills_arena.category.communication': 'Comunicación',
    'skills_arena.category.balance': 'Equilibrio',
    'skills_arena.category.leadership': 'Liderazgo',
    'skills_arena.category.emotional': 'Inteligencia Emocional',
    // Skills Arena Difficulties
    'skills_arena.difficulty.beginner': 'Principiante',
    'skills_arena.difficulty.intermediate': 'Intermedio',
    'skills_arena.difficulty.advanced': 'Avanzado',
    // Skills Arena Tests
    'skills_arena.tests.personal_brand.title': 'Marca Personal',
    'skills_arena.tests.personal_brand.description': 'Descubre tu esencia y construye una identidad profesional auténtica',
    'skills_arena.tests.wheel_of_life.title': 'Rueda de la Vida',
    'skills_arena.tests.wheel_of_life.description': 'Evalúa el equilibrio en las diferentes áreas de tu vida',
    'skills_arena.tests.active_listening.title': 'Escucha Activa',
    'skills_arena.tests.active_listening.description': 'Mide tu capacidad de escuchar y comprender a los demás',
    'skills_arena.tests.empathy_quotient.title': 'Cociente de Empatía',
    'skills_arena.tests.empathy_quotient.description': 'Descubre tu nivel de empatía y conexión emocional',
    'skills_arena.tests.leadership_style.title': 'Estilo de Liderazgo',
    'skills_arena.tests.leadership_style.description': 'Identifica tu estilo de liderazgo natural',
    'skills_arena.tests.conflict_resolution.title': 'Resolución de Conflictos',
    'skills_arena.tests.conflict_resolution.description': 'Evalúa tu habilidad para manejar y resolver conflictos',

    // Wheel of Life
    'wheel_of_life.title': 'Rueda de la Vida',
    'wheel_of_life.intro_description': 'Evalúa 12 áreas clave de tu vida. Identifica tus fortalezas, debilidades y las brechas más grandes entre tu situación actual y la deseada.',
    'wheel_of_life.areas_count': 'áreas de vida',
    'wheel_of_life.start': 'Comenzar',
    'wheel_of_life.start_new': 'Empezar de nuevo',
    'wheel_of_life.continue_progress': 'Continuar donde dejé',
    'wheel_of_life.current_score': 'Puntuación actual',
    'wheel_of_life.desired_score': 'Puntuación deseada',
    'wheel_of_life.score_low': 'Muy bajo',
    'wheel_of_life.score_high': 'Excelente',
    'wheel_of_life.reason_label': '¿Por qué esta puntuación?',
    'wheel_of_life.reason_placeholder': 'Opcional: describe brevemente tu situación en esta área...',
    'wheel_of_life.optional': 'opcional',
    'wheel_of_life.next': 'Siguiente',
    'wheel_of_life.previous': 'Anterior',
    'wheel_of_life.review': 'Revisar',
    'wheel_of_life.edit': 'Editar',
    'wheel_of_life.submit': 'Enviar resultados',
    'wheel_of_life.submitting': 'Enviando...',
    'wheel_of_life.review_title': 'Revisa tus respuestas',
    'wheel_of_life.review_description': 'Toca cualquier área para editarla antes de enviar',
    'wheel_of_life.current': 'Actual',
    'wheel_of_life.desired': 'Deseado',
    'wheel_of_life.gap': 'Brecha',
    'wheel_of_life.results_title': 'Tus Resultados',
    'wheel_of_life.balance_score': 'Puntaje de Equilibrio',
    'wheel_of_life.avg_current': 'prom. actual',
    'wheel_of_life.avg_desired': 'prom. deseado',
    'wheel_of_life.your_wheel': 'Tu Rueda de la Vida',
    'wheel_of_life.strengths': 'Tus Fortalezas',
    'wheel_of_life.weaknesses': 'Áreas de Mejora',
    'wheel_of_life.biggest_gaps': 'Brechas más Grandes',
    'wheel_of_life.recommendations': 'Recomendaciones',
    'wheel_of_life.back_to_arena': 'Volver al Arena',
    'wheel_of_life.play_again': 'Jugar de nuevo',
    'wheel_of_life.first_attempt_bonus': '¡Bonus de primer intento!',
    'wheel_of_life.total_xp': 'XP Total',
    // Wheel of Life - Areas
    'wheel_of_life.area.trabajo': 'Trabajo',
    'wheel_of_life.area.dinero': 'Dinero',
    'wheel_of_life.area.salud': 'Salud',
    'wheel_of_life.area.amor': 'Amor',
    'wheel_of_life.area.crecimiento_personal': 'Crecimiento Personal',
    'wheel_of_life.area.diversion': 'Diversión',
    'wheel_of_life.area.entorno_fisico': 'Entorno Físico',
    'wheel_of_life.area.espiritualidad': 'Espiritualidad',
    'wheel_of_life.area.amigos': 'Amigos',
    'wheel_of_life.area.familia': 'Familia',
    'wheel_of_life.area.alimentacion': 'Alimentación',
    'wheel_of_life.area.ejercicio_fisico': 'Ejercicio Físico',
    // Wheel of Life - Area Descriptions
    'wheel_of_life.area_desc.trabajo': '¿Qué tan satisfecho estás con tu carrera y trabajo actual?',
    'wheel_of_life.area_desc.dinero': '¿Cómo te sientes respecto a tu situación financiera?',
    'wheel_of_life.area_desc.salud': '¿Cómo está tu salud física y mental en general?',
    'wheel_of_life.area_desc.amor': '¿Cómo va tu vida romántica y relaciones de pareja?',
    'wheel_of_life.area_desc.crecimiento_personal': '¿Estás creciendo y aprendiendo constantemente?',
    'wheel_of_life.area_desc.diversion': '¿Dedicas tiempo suficiente a la diversión y el ocio?',
    'wheel_of_life.area_desc.entorno_fisico': '¿Tu hogar y entorno te hacen sentir cómodo?',
    'wheel_of_life.area_desc.espiritualidad': '¿Tienes paz interior y conexión espiritual?',
    'wheel_of_life.area_desc.amigos': '¿Cómo es la calidad de tus amistades?',
    'wheel_of_life.area_desc.familia': '¿Cómo es tu relación con tu familia?',
    'wheel_of_life.area_desc.alimentacion': '¿Cómo es tu alimentación y hábitos nutricionales?',
    'wheel_of_life.area_desc.ejercicio_fisico': '¿Realizas actividad física de forma regular?',
    // Wheel of Life - Recommendations
    'wheel_of_life.recommendation.trabajo': 'Reflexiona sobre lo que realmente te apasiona en tu carrera. Considera hablar con un mentor o explorar nuevas oportunidades de desarrollo profesional.',
    'wheel_of_life.recommendation.dinero': 'Crea un presupuesto mensual y establece metas financieras a corto y largo plazo. Considera buscar asesoría financiera.',
    'wheel_of_life.recommendation.salud': 'Prioriza tu bienestar con chequeos regulares, manejo del estrés y buenos hábitos de sueño.',
    'wheel_of_life.recommendation.amor': 'Invierte tiempo de calidad en tus relaciones. La comunicación abierta y la vulnerabilidad son clave.',
    'wheel_of_life.recommendation.crecimiento_personal': 'Establece un hábito de aprendizaje diario: lectura, cursos, o nuevas experiencias que te desafíen.',
    'wheel_of_life.recommendation.diversion': 'Programa tiempo para actividades que disfrutes. El ocio es esencial para la creatividad y el bienestar.',
    'wheel_of_life.recommendation.entorno_fisico': 'Dedica tiempo a organizar y mejorar tu espacio. Un entorno ordenado impacta positivamente tu mente.',
    'wheel_of_life.recommendation.espiritualidad': 'Explora prácticas de meditación, mindfulness o cualquier actividad que te conecte con tu propósito.',
    'wheel_of_life.recommendation.amigos': 'Cultiva tus amistades activamente. Planifica encuentros regulares y sé intencional con tus conexiones.',
    'wheel_of_life.recommendation.familia': 'Fortalece los lazos familiares con comunicación regular y tiempo de calidad juntos.',
    'wheel_of_life.recommendation.alimentacion': 'Adopta una alimentación más consciente. Planifica tus comidas y aumenta el consumo de frutas y verduras.',
    'wheel_of_life.recommendation.ejercicio_fisico': 'Comienza con 30 minutos de actividad física 3 veces por semana. Encuentra una actividad que disfrutes.',

    // Gamified Dashboard
    'nav.gamified_dashboard': 'Dashboard Gamificado',
    'nav.desc.gamified_dashboard': 'Tu progreso con montaña, logros y ranking',
    'nav.gamified_dashboard_v2': 'Dashboard V2',
    'nav.desc.gamified_dashboard_v2': 'Nueva version con radar, insignias y actividad',
    'nav.team_dashboard': 'Dashboard Equipo',
    'nav.desc.team_dashboard': 'Rendimiento y métricas del equipo para líderes',
    'gamified.mountain_title': 'Montaña de Fuego',
    'gamified.streak_days': 'Días Racha',
    'gamified.yesterday': 'AYER',
    'gamified.today': 'HOY',
    'gamified.daily_climb': 'Escalada Diaria',
    'gamified.rewards': 'Recompensas',
    'gamified.filler_words': 'Muletillas',
    'gamified.ranking': 'Ranking',
    'gamified.feedback': 'Feedback',
    'gamified.insight': 'Insight',
    'gamified.progress_listen': 'Escucha',
    'gamified.progress_security': 'Seguridad',
    'gamified.progress_speak': 'Speak',

    // Omi Admin Insights
    'omi_insights.title': 'Omi Platform Insights',
    'omi_insights.description': 'Analíticas de conversaciones a nivel plataforma y proyecciones de escalabilidad',
    'omi_insights.error_title': 'Error',
    'omi_insights.error_loading': 'Error al cargar los insights de Omi',
    'omi_insights.total_conversations': 'Total Conversaciones',
    'omi_insights.segments': 'segmentos',
    'omi_insights.active_users': 'Usuarios Activos',
    'omi_insights.of_total': 'del total',
    'omi_insights.avg_per_user': 'Promedio por Usuario',
    'omi_insights.median': 'Mediana',
    'omi_insights.with_feedback': 'Con Feedback',
    'omi_insights.analyzed': 'analizadas',
    'omi_insights.avg_duration': 'Duración Promedio',
    'omi_insights.words_avg': 'palabras promedio',
    'omi_insights.avg_segments': 'Segmentos Promedio',
    'omi_insights.per_transcript': 'por transcripción',
    'omi_insights.avg_score': 'Puntuación Promedio',
    'omi_insights.communication_quality': 'Calidad de comunicación',
    'omi_insights.scalability_title': 'Escalabilidad a 600 usuarios',
    'omi_insights.scalability_description': 'Proyección de almacenamiento para {users} usuarios',
    'omi_insights.current_storage': 'Almacenamiento Actual',
    'omi_insights.per_user': 'usuario',
    'omi_insights.projected_storage': 'Proyección',
    'omi_insights.for_users': 'para {users} usuarios',
    'omi_insights.tier_usage': 'Uso del tier',
    'omi_insights.of': 'de',
    'omi_insights.recommended_tier': 'Tier recomendado',
    'omi_insights.tier_comfortable': 'Capacidad cómoda para el crecimiento proyectado',
    'omi_insights.tier_adequate': 'Capacidad adecuada, monitorear crecimiento',
    'omi_insights.tier_tight': 'Capacidad ajustada, considerar upgrade',
    'omi_insights.growth_title': 'Tendencias de Crecimiento',
    'omi_insights.growth_description': 'Actividad de conversaciones recientes',
    'omi_insights.last_7_days': 'Últimos 7 días',
    'omi_insights.last_30_days': 'Últimos 30 días',
    'omi_insights.per_day': 'día',
    'omi_insights.growth_rate': 'Tasa de Crecimiento',
    'omi_insights.vs_30_day_avg': 'vs promedio 30 días',
  },
  en: {
    // Navigation
    'nav.features': 'Features',
    'nav.success_cases': 'Success Cases',
    'nav.login': 'Login',
    'nav.start_free': 'Start Free',
    'nav.navigation': 'Navigation',
    'nav.logout': 'Logout',
    'nav.first_interview': 'My First Interview',
    'nav.interview_history': 'Interview History',
    
    // Hero Section
    'hero.badge': 'AI · Mentoring · Daily Growth',
    'hero.title_part1': 'doesn\'t train you for a course.',
    'hero.title_part2': 'It transforms you forever.',
    'hero.description': 'Your artificial intelligence mentor that drives the evolution and daily growth of IT teams. A challenging, emotionally intelligent and visionary experience.',
    'hero.start_evolution': 'Start Your Evolution',
    'hero.watch_demo': 'Watch Demo',
    
    // Features Section
    'features.title': 'How does',
    'features.description': 'A complete platform that combines artificial intelligence, gamification and personalized mentoring to accelerate your team\'s growth.',
    'features.dashboard.title': 'Personalized Dashboard',
    'features.dashboard.description': 'Visualize progress metrics, completed sessions and active day streaks in real time.',
    'features.workplan.title': 'Visual Work Plan',
    'features.workplan.description': 'Personalized learning paths with clear modules and objectives in interactive format.',
    'features.achievements.title': 'Achievement System',
    'features.achievements.description': 'Badges, XP and leaderboards that motivate consistency and celebrate every milestone achieved.',
    'features.calendar.title': 'Smart Calendar',
    'features.calendar.description': 'Mentoring sessions synchronized with Google Calendar and Outlook for perfect organization.',
    
    // Benefits Section
    'benefits.title': 'More than a tool, a growth companion',
    'benefits.description': 'is not just technology. It\'s an experience designed to create authentic human connections while enhancing the professional development of each team member.',
    'benefits.mentoring': 'Personalized mentoring based on advanced AI',
    'benefits.integration': 'Perfect integration with existing tools',
    'benefits.automation': 'Intelligent workflow automation',
    'benefits.metrics': 'Clear progress and ROI metrics',
    'benefits.humanity.title': 'Augmented Humanity',
    'benefits.humanity.description': 'Technology that enhances human connection, doesn\'t replace it. Every interaction is designed to be authentic, challenging and transformative.',
    
    // Testimonials
    'testimonials.title': 'What our users say',
    'testimonials.subtitle': 'IT leaders who are already transforming their teams with',
    'testimonials.carlos.content': 'The platform has revolutionized how we develop talent in our team. Results are measurable and engagement has increased by 300%.',
    'testimonials.ana.content': 'Gamification really works. Our developers are more motivated and soft skills have improved significantly.',
    'testimonials.roberto.content': 'The platform\'s automation saves us 10 hours weekly in team management, allowing us to focus on what really matters.',
    
    // CTA Section
    'cta.title': 'Ready to transform your team?',
    'cta.description': 'Join hundreds of IT leaders who are already seeing real results. Start your free trial today and discover your team\'s potential.',
    'cta.start_trial': 'Start Free Trial',
    'cta.schedule_demo': 'Schedule Demo',
    
    // Footer
    'footer.copyright': 'Transforming the future of IT learning.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.home': 'Dashboard',
    'dashboard.org.title': 'My Organization Dashboard',
    'dashboard.org.description': 'View your team and organizational progress',
    'dashboard.stats.team_sessions': 'Team Sessions',
    'dashboard.stats.organization_total': 'Organization total',
    'dashboard.stats.active': 'Active',
    'dashboard.stats.in_progress': 'In progress or scheduled',
    'dashboard.stats.performance': 'Performance',
    'dashboard.stats.completion_rate': 'Team completion rate',
    'dashboard.stats.team_wellbeing': 'Team Wellbeing',
    'dashboard.stats.average_mood': 'Average mood',
    'dashboard.charts.monthly_performance': 'Monthly Team Performance',
    'dashboard.charts.monthly_description': 'Your organization\'s progress by month',
    'dashboard.charts.team_sessions': 'Team Sessions',
    'dashboard.charts.completed': 'Completed',
    'dashboard.charts.team_status': 'Team Status',
    'dashboard.charts.status_description': 'Session distribution',
    'dashboard.charts.weekly_activity': 'Weekly Team Activity',
    'dashboard.charts.weekly_description': 'Daily sessions from your organization',
    
    // Dashboard User
    'dashboard.user.title': 'My Dashboard',
    'dashboard.user.greeting': 'Hello',
    'dashboard.user.user': 'User',
    'dashboard.user.description': 'Here is your personal coaching progress',
    'dashboard.user.radar_title': '360° Competency Assessment',
    'dashboard.user.radar_description': 'Comparison between your self-assessment and your coach\'s assessment',
    'dashboard.user.my_sessions': 'My Sessions',
    'dashboard.user.upcoming': 'Upcoming',
    'dashboard.user.consistency': 'My Consistency',
    'dashboard.user.wellbeing': 'My Wellbeing',
    'dashboard.user.sessions_completed': 'Sessions completed',
    'dashboard.user.sessions_scheduled': 'Scheduled sessions',
    'dashboard.user.attendance_rate': 'Attendance rate',
    'dashboard.user.average_mood': 'Average mood',
    'dashboard.user.monthly_progress': 'My Monthly Progress',
    'dashboard.user.monthly_description': 'Your evolution in recent months',
    'dashboard.user.sessions_status': 'My Sessions',
    'dashboard.user.status_description': 'Status of your sessions',
    'dashboard.user.weekly_activity': 'My Weekly Activity',
    'dashboard.user.weekly_description': 'Your sessions in the last week',
    'dashboard.user.clarity': 'Clarity (C)',
    'dashboard.user.structure': 'Structure (S)',  
    'dashboard.user.emotional_alignment': 'Emotional Alignment (A)',
    'dashboard.user.action_influence': 'Action & Influence (I)',
    'dashboard.user.my_evaluation': 'My Assessment',
    'dashboard.user.coach_evaluation': 'Coach Assessment',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.coach': 'Coach',
    'nav.roleplay': 'Training Room',
    'nav.demo': 'Demo',
    'nav.demo_training': 'Demo Training',
    'nav.roleplay_progress': 'Mi Progreso',
    'nav.learning_path': 'Learning Path',
    'nav.team_learning_progress': 'Team Progress',
    'nav.sessions': 'Historial',
    'nav.analytics': 'Analytics',
    'nav.organizations': 'Organizations',
    'nav.users': 'Users',
    'nav.reports': 'Reports',
    'nav.trends': 'Trends',
    'nav.plans': 'Plans',
    'nav.documents': 'Documents',
    'nav.settings': 'Settings',
    'nav.my_team': 'My Team',
    'nav.plan': 'Plan',
    'nav.achievements': 'Achievements',
    
    // Roles
    'roles.admin': 'Global Administrator',
    'roles.manager': 'Administrator',
    'roles.user': 'User',
    'roles.default_user': 'User',
    'dashboard.analytics': 'Analytics',
    'dashboard.reports': 'Reports',
    'dashboard.trends': 'Trends',
    'dashboard.users': 'Users',
    'dashboard.plans': 'Plans',
    'dashboard.settings': 'Settings',
    'dashboard.team.title': 'My Team',
    'dashboard.team.description': 'Manage and administer your team members',
    'dashboard.team.upload_csv': 'Upload Users from CSV',
    'dashboard.team.upload_description': 'Import multiple users to your team using a CSV file',
    'dashboard.team.download_template': 'Download Template',
    'dashboard.team.processing': 'Processing CSV file...',
    'dashboard.team.results_title': 'Upload Results',
    'dashboard.team.successful': 'Successful',
    'dashboard.team.failed': 'Failed',
    'dashboard.team.total': 'Total',
    'dashboard.team.errors': 'Errors',
    'dashboard.team.format_required': 'Required format',
    'dashboard.team.members': 'Team Members',
    'dashboard.team.members_description': 'List of all your team members and their current status',
    'dashboard.team.name': 'Name',
    'dashboard.team.email': 'Email',
    'dashboard.team.role': 'Role',
    'dashboard.team.status': 'Status',
    'dashboard.team.join_date': 'Join Date',
    'dashboard.team.status_active': 'Active',
    'dashboard.team.status_pending': 'Pending',
    'dashboard.team.status_suspended': 'Suspended',
    'dashboard.team.upload_success': 'Upload completed',
    'dashboard.team.upload_error': 'Upload error',
    'dashboard.team.template_downloaded': 'Template downloaded',
    'dashboard.team.csv_error': 'Please select a valid CSV file',

    // Coach
    'coach.title': 'AI Coach',
    'coach.subtitle': 'Your personal mentor for professional growth',
    'coach.ai_coach': 'Artificial Intelligence Coach',
    'coach.description': 'Chat with your AI-powered personal coach for personalized mentoring',
    'coach.status.ready': 'Ready to chat',
    'coach.status.connecting': 'Connecting...',
    'coach.status.listening': 'Listening...',
    'coach.status.thinking': 'Processing...',
    'coach.status.speaking': 'Responding...',
    'coach.start_listening': 'Start Conversation',
    'coach.stop_listening': 'Stop',
    'coach.mute': 'Mute',
    'coach.unmute': 'Unmute',
    'coach.instructions': 'Write your query and get personalized coaching in real time',
    'coach.error.no_api_key': 'Demo mode - Full voice integration requires configuration',
    'coach.new_conversation': 'New Conversation',
    'coach.voice_mode': 'Voice Mode (Coming Soon)',
    'coach.placeholder': 'Write your coaching query...',
    'coach.thinking': 'Your coach is thinking...',
    'coach.specialties': 'Your intelligent coach is ready to help you with leadership, productivity and professional development',

    // AI Resources
    'nav.ai_resources': 'AI Educational Resources',
    'ai_resources.title': 'AI Educational Resources',
    'ai_resources.description': 'Artificial intelligence resources for training',
    'ai_resources.open_resource': 'Open Resource',
    'ai_resources.add_resource': 'Add Resource',
    'ai_resources.add_title': 'New Educational Resource',
    'ai_resources.form.title': 'Title',
    'ai_resources.form.title_placeholder': 'Resource name',
    'ai_resources.form.description': 'Description',
    'ai_resources.form.description_placeholder': 'Brief description of the resource',
    'ai_resources.form.url': 'Resource URL',
    'ai_resources.form.url_placeholder': 'https://example.com',
    'ai_resources.form.icon': 'Icon',
    'ai_resources.form.color': 'Color',
    'ai_resources.form.submit': 'Save Resource',
    'ai_resources.form.cancel': 'Cancel',
    'ai_resources.success': 'Resource added successfully',
    'ai_resources.error': 'Error adding resource',
    'ai_resources.loading': 'Loading resources...',
    'ai_resources.empty': 'No resources available',

    // Learning Content (Library)
    'nav.learning_content': 'Library',
    'nav.desc.learning_content': 'Videos, podcasts and study materials',
    'learning_content.title': 'Content Library',
    'learning_content.description': 'Explore videos, podcasts, PDFs and articles to keep learning',
    'learning_content.add': 'Add Content',
    'learning_content.add_title': 'New Content',
    'learning_content.loading': 'Loading content...',
    'learning_content.empty': 'No content available yet',
    'learning_content.error': 'Error loading content',
    'learning_content.open': 'Open resource',
    'learning_content.all': 'All',
    'learning_content.videos': 'Videos',
    'learning_content.podcasts': 'Podcasts',
    'learning_content.pdfs': 'PDFs',
    'learning_content.articles': 'Articles',
    'learning_content.form.title': 'Title',
    'learning_content.form.description': 'Description',
    'learning_content.form.url': 'Resource URL',
    'learning_content.form.type': 'Content type',
    'learning_content.form.thumbnail': 'Thumbnail URL (optional)',
    'learning_content.form.duration': 'Duration (optional)',
    'learning_content.form.cancel': 'Cancel',
    'learning_content.form.submit': 'Create',
    'learning_content.success': 'Content created successfully',
    'learning_content.delete_success': 'Content deleted',
    'learning_content.type.video': 'Video',
    'learning_content.type.podcast': 'Podcast',
    'learning_content.type.pdf': 'PDF',
    'learning_content.type.article': 'Article',

    // Avatar Showcase
    'nav.avatar_showcase': 'Avatar Showcase',
    'avatar_showcase.title': 'Voxel Avatar Showcase',
    'avatar_showcase.description': 'Compare different approaches for rendering 3D voxel-style avatars',

    // Navigation - Additional items
    'nav.avatar': 'My Avatar',
    'nav.stats': 'My Stats',
    'nav.agent_config': 'Agent Config',
    'nav.welcome': 'Hello',
    'nav.welcome_subtitle': 'What would you like to do today?',

    // Navigation - Card descriptions
    'nav.desc.dashboard': 'Your home page',
    'nav.desc.avatar': 'Customize your 3D avatar',
    'nav.desc.stats': 'Metrics and charts of your progress',
    'nav.desc.first_interview': 'Structured initial interview',
    'nav.desc.roleplay': 'Practice scenarios with AI',
    'nav.desc.learning_path': 'Your development path',
    'nav.desc.progress': 'View your progress and metrics',
    'nav.desc.sessions': 'Session history',
    'nav.desc.team_progress': 'Your team progress',
    'nav.desc.my_team': 'Manage your team',
    'nav.desc.plans': 'Subscription plans',
    'nav.desc.documents': 'Team documents',
    'nav.desc.settings': 'Account settings',
    'nav.desc.coach': 'Chat with your AI coach',
    'nav.desc.agent_config': 'Configure profiles and scenarios',
    'nav.desc.ai_resources': 'AI educational resources',
    'nav.desc.avatar_showcase': 'Avatar gallery',
    'nav.desc.demo': 'Try the platform',
    'nav.desc.demo_training': 'Demo training',
    'nav.desc.analytics': 'Platform metrics',
    'nav.desc.organizations': 'Manage organizations',
    'nav.desc.users': 'Manage users',
    'nav.desc.reports': 'Detailed reports',
    'nav.desc.trends': 'Trends and patterns',
    'nav.desc.tech_week': 'Tech Week special event',
    'nav.desc.interview_history': 'Interview history',
    'nav.desc.hero_journey': 'Visualize your path as a mountain',
    'nav.hero_journey': "Hero's Journey",
    'nav.omi_conversations': 'My Conversations',
    'nav.desc.omi_conversations': 'Omi recordings and analysis',
    'nav.web_recorder': 'Web Recorder',
    'nav.desc.web_recorder': 'Record conversations from your browser',

    // Web Recorder
    'recorder.speaker_you': 'You',
    'recorder.participants_detected': 'Participants Detected',
    'recorder.participant': 'Participant',
    'recorder.words': 'words',
    'recorder.guard_title': 'Recording in Progress',
    'recorder.guard_description': 'You have an active recording. What would you like to do?',
    'recorder.guard_cancel': 'Continue Recording',
    'recorder.guard_confirm': 'Save and Exit',
    'recorder.guard_saving': 'Saving...',

    // Navigation - Section headers
    'nav.section.profile': 'My Profile',
    'nav.section.profile_desc': 'Your personal information',
    'nav.section.practice': 'Practice',
    'nav.section.practice_desc': 'Improve your communication skills',
    'nav.section.progress': 'My Progress',
    'nav.section.progress_desc': 'Review your progress and results',
    'nav.section.team': 'My Team',
    'nav.section.team_desc': 'Team management and tracking',
    'nav.section.config': 'Settings',
    'nav.section.config_desc': 'Settings and documents',
    'nav.section.admin': 'Administration',
    'nav.section.admin_desc': 'Admin tools',

    // Omi Conversations
    'omi.page_description': 'Review your recorded conversations and analysis',
    'omi.error_loading': 'Error loading conversations',
    'omi.no_conversations': 'No conversations',
    'omi.no_conversations_desc': 'Your recorded Omi conversations will appear here',
    'omi.communication_analysis': 'Communication Analysis',
    'omi.overall_score': 'Overall Score',
    'omi.clarity': 'Clarity',
    'omi.engagement': 'Engagement',
    'omi.structure': 'Structure',
    'omi.strengths': 'Strengths',
    'omi.areas_to_improve': 'Areas to Improve',
    'omi.insights': 'Communication Insights',
    'omi.objections': 'Objection Handling',
    'omi.calls_to_action': 'Calls to Action',
    'omi.action_items': 'Action Items',
    'omi.events': 'Events',
    'omi.transcript': 'Transcript',
    'omi.no_transcript': 'No transcript available',
    // Omi Radiografía (extended analysis)
    'omi.radiografia': 'Communication X-Ray',
    'omi.muletillas': 'Filler Words',
    'omi.muletillas_detected': 'Filler Words Detected',
    'omi.muletillas_frequency': 'Filler word frequency',
    'omi.talk_ratio': 'Talk Ratio',
    'omi.balanced': 'Balanced',
    'omi.unbalanced': 'Unbalanced',
    'omi.words_user': 'Your Words',
    'omi.you': 'You',
    'omi.others': 'Others',
    'omi.questions': 'Questions',
    'omi.your_questions': 'Your Questions',
    'omi.questions_received': 'Questions Received',
    'omi.no_questions': 'No questions recorded',
    'omi.topics': 'Topics Discussed',
    'omi.your_commitments': 'Your Commitments',
    'omi.with_date': 'with date',
    'omi.without_date': 'without date',
    'omi.open_topics': 'Open Topics',
    'omi.reason': 'Reason',
    'omi.delete_conversation': 'Delete conversation?',
    'omi.delete_conversation_description': 'This action will mark the conversation as deleted.',
    'omi.reanalyze': 'Reanalyze',
    'omi.conversation_id': 'ID',
    'omi.copy_id': 'Copy ID',
    'omi.id_copied': 'ID copied',
    // Omi Analysis Sections
    'omi.analysis_title': 'Your Communication Analysis',
    'omi.minutes': 'minutes',
    'omi.words_analyzed': 'words analyzed',
    'omi.summary_section': 'Summary',
    'omi.quick_radiography': 'Quick Overview',
    'omi.communication_metrics': 'Communication Metrics',
    'omi.muletillas_section': 'Filler Words Detected',
    'omi.questions_section': 'Question Analysis',
    'omi.topics_section': 'Topics Discussed',
    'omi.commitments_section': 'Your Commitments',
    'omi.pending_section': 'Pending Topics',
    'omi.strengths_section': 'Strengths to Maintain',
    'omi.areas_section': 'Areas for Improvement',
    'omi.transcript_section': 'Transcript',
    'omi.of_10_points': 'out of 10 points',
    'omi.score_excellent': 'Excellent',
    'omi.score_good': 'Good job',
    'omi.score_developing': 'Developing',
    'omi.no_feedback_available': 'No feedback available for this conversation.',
    'omi.level_excellent': 'Excellent',
    'omi.level_good': 'Good',
    'omi.level_developing': 'Developing',
    'omi.level_needs_work': 'Needs work',
    'omi.participant': 'Participant',
    'omi.new_recording': 'New Recording',
    // KPI Grid translations
    'omi.no_muletillas': 'No filler words',
    'omi.balanced_conversation': 'Balanced conversation',
    'omi.you_talk_more': 'You talk more than others',
    'omi.others_talk_more': 'Others talk more',
    'omi.no_questions_data': 'No questions data',
    'omi.words_others': 'Others\' Words',
    'omi.total': 'Total',
    'omi.no_topics': 'No topics identified',
    'omi.commitments': 'Commitments',
    'omi.no_commitments': 'No commitments',
    'omi.all_closed': 'All topics closed',
    // Score descriptions
    'omi.clarity_desc_high': 'Clear and precise communication',
    'omi.clarity_desc_medium': 'Some areas can improve',
    'omi.clarity_desc_low': 'Filler words hinder understanding',
    'omi.structure_desc_high': 'Well-organized ideas',
    'omi.structure_desc_medium': 'Structure can improve',
    'omi.structure_desc_low': 'Disorganized ideas',
    'omi.empatia': 'Empathy',
    'omi.vocabulario': 'Vocabulary',
    'omi.objetivo': 'Purpose',
    'omi.empatia_desc_high': 'Excellent listening and connection',
    'omi.empatia_desc_medium': 'Active listening can improve',
    'omi.empatia_desc_low': 'Little focus on listening to others',
    'omi.vocabulario_desc_high': 'Rich and appropriate vocabulary',
    'omi.vocabulario_desc_medium': 'Adequate vocabulary',
    'omi.vocabulario_desc_low': 'Limited or colloquial vocabulary',
    'omi.objetivo_desc_high': 'Very focused conversation with clear actions',
    'omi.objetivo_desc_medium': 'Some topics without concrete closure',
    'omi.objetivo_desc_low': 'No clear objectives or commitments',
    'omi.conversation_not_found': 'Conversation not found',
    'omi.conversation_not_found_desc': 'The conversation you are looking for does not exist or you do not have access to it.',
    'omi.back_to_conversations': 'Back to conversations',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.processing': 'Processing...',

    // Dashboard - Omi Stats Section
    'dashboard.user.omi_section': 'My Omi Conversations',
    'dashboard.user.omi_description': 'Analysis of your recorded conversations',
    'dashboard.user.omi_avg_scores': 'Average Scores',
    'dashboard.user.omi_evolution': 'Score Evolution',
    'dashboard.user.omi_total_conversations': 'Conversations',
    'dashboard.user.omi_avg_score': 'Average Score',
    'dashboard.user.omi_total_time': 'Total Time',
    'dashboard.user.omi_no_data': 'No conversation data',
    'dashboard.user.omi_no_data_desc': 'Record conversations with Omi to see your analysis here',
    'dashboard.user.omi_overall': 'Overall',

    // Meeting Analysis
    'nav.meeting_analysis': 'Meeting Analysis',
    'nav.desc.meeting_analysis': 'Communication analysis dashboard for meetings',

    // SVG Converter
    'nav.svg_converter': 'SVG Converter',
    'nav.desc.svg_converter': 'Convert images to SVG and manage assets',

    // Recorder Logs
    'nav.recorder_logs': 'Recorder Logs',
    'nav.desc.recorder_logs': 'Debug logs from web recorder sessions',

    'svg_converter.title': 'SVG Converter',
    'svg_converter.description': 'Convert images to vectors and manage your asset gallery',
    'svg_converter.tab_convert': 'Convert',
    'svg_converter.tab_gallery': 'Gallery',
    'svg_converter.drag_drop_or_click': 'Drag an image or click to select',
    'svg_converter.drop_here': 'Drop the image here',
    'svg_converter.supported_formats': 'Supported formats: JPG, PNG, WebP',
    'svg_converter.max_file_size': 'Max file size: 5MB',
    'svg_converter.error_invalid_format': 'Invalid file format. Use JPG, PNG or WebP.',
    'svg_converter.error_file_too_large': 'File is too large. Maximum 5MB.',
    'svg_converter.settings_title': 'Settings',
    'svg_converter.preset_label': 'Image type',
    'svg_converter.preset_photo': 'Photo',
    'svg_converter.preset_logo': 'Logo',
    'svg_converter.preset_illustration': 'Illustration',
    'svg_converter.preset_line_art': 'Line Art',
    'svg_converter.color_count_label': 'Color count',
    'svg_converter.color_count_hint': 'Fewer colors = smaller file',
    'svg_converter.original': 'Original',
    'svg_converter.converted': 'Converted SVG',
    'svg_converter.converting': 'Converting...',
    'svg_converter.no_preview': 'No preview',
    'svg_converter.error_conversion_failed': 'Error converting image',
    'svg_converter.warning_large_svg': 'Generated SVG is large ({size} KB). Consider reducing colors.',
    'svg_converter.reset': 'New image',
    'svg_converter.download': 'Download',
    'svg_converter.save_to_gallery': 'Save to gallery',
    'svg_converter.save_dialog_title': 'Save asset',
    'svg_converter.save_dialog_description': 'Add information to save this SVG to the gallery',
    'svg_converter.field_name': 'Name',
    'svg_converter.field_name_placeholder': 'Asset name',
    'svg_converter.field_description': 'Description',
    'svg_converter.field_description_placeholder': 'Optional description',
    'svg_converter.field_category': 'Category',
    'svg_converter.field_tags': 'Tags',
    'svg_converter.field_tags_placeholder': 'logo, icon, banner',
    'svg_converter.field_tags_hint': 'Comma separated',
    'svg_converter.category_general': 'General',
    'svg_converter.category_icons': 'Icons',
    'svg_converter.category_illustrations': 'Illustrations',
    'svg_converter.category_logos': 'Logos',
    'svg_converter.category_backgrounds': 'Backgrounds',
    'svg_converter.category_patterns': 'Patterns',
    'svg_converter.save': 'Save',
    'svg_converter.success': 'Success',
    'svg_converter.error': 'Error',
    'svg_converter.error_name_required': 'Name is required',
    'svg_converter.error_save_failed': 'Error saving asset',
    'svg_converter.asset_saved': 'Asset saved successfully',
    'svg_converter.search_placeholder': 'Search assets...',
    'svg_converter.all_categories': 'All categories',
    'svg_converter.loading': 'Loading...',
    'svg_converter.error_loading': 'Error loading assets',
    'svg_converter.no_assets': 'No assets',
    'svg_converter.no_assets_hint': 'Convert an image to create your first asset',
    'svg_converter.inactive': 'Inactive',
    'svg_converter.active': 'Active',
    'svg_converter.asset_details': 'Asset details',
    'svg_converter.asset_details_description': 'Asset information and actions',
    'svg_converter.edit_asset': 'Edit asset',
    'svg_converter.edit_asset_description': 'Modify asset information',
    'svg_converter.edit': 'Edit',
    'svg_converter.delete': 'Delete',
    'svg_converter.copy_svg': 'Copy SVG',
    'svg_converter.copied': 'Copied',
    'svg_converter.error_copy_failed': 'Error copying',
    'svg_converter.activate': 'Activate',
    'svg_converter.deactivate': 'Deactivate',
    'svg_converter.asset_updated': 'Asset updated',
    'svg_converter.asset_activated': 'Asset activated',
    'svg_converter.asset_deactivated': 'Asset deactivated',
    'svg_converter.error_update_failed': 'Error updating',
    'svg_converter.delete_confirm_title': 'Delete asset?',
    'svg_converter.delete_confirm_description': 'This action will deactivate the asset. You can reactivate it later.',
    'svg_converter.asset_deleted': 'Asset deleted',
    'svg_converter.error_delete_failed': 'Error deleting',

    // Desktop App Download
    'nav.desktop_app': 'Desktop App',
    'nav.desc.desktop_app': 'Download Maity for your computer',
    'download.title': 'Desktop App',
    'download.subtitle': 'Download Maity for your computer',
    'download.description': 'Install the desktop application for an optimized experience',
    'download.version': 'Version',
    'download.download_for': 'Download for',
    'download.recommended': 'Recommended for you',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.other_platforms': 'Other platforms',
    'download.features_title': 'Features',
    'download.feature_offline': 'Offline access',
    'download.feature_notifications': 'Native notifications',
    'download.feature_performance': 'Better performance',
    'download.feature_auto_updates': 'Automatic updates',
    'download.requirements_windows': 'Windows 10 or later (64-bit)',
    'download.requirements_macos': 'macOS 10.15 or later',
    'download.coming_soon': 'Coming soon',
    'download.windows_available': 'In the meantime, the Windows version is available:',
    'download.view_all_releases': 'View all releases',
    'download.loading': 'Loading download information...',
    'download.error': 'Error loading',
    'download.error_description': 'Could not get download information. Please try again later.',
    'download.retry': 'Retry',

    // Skills Arena
    'nav.skills_arena': 'Skills Arena',
    'nav.desc.skills_arena': 'Tests and games to develop soft skills',
    'skills_arena.title': 'Skills Arena',
    'skills_arena.subtitle': 'Welcome, {name}! Challenge your skills.',
    'skills_arena.featured': 'FEATURED',
    'skills_arena.start': 'Start',
    'skills_arena.continue': 'Continue',
    'skills_arena.completed': 'Completed',
    'skills_arena.locked': 'Locked',
    'skills_arena.progress': 'Progress',
    'skills_arena.questions': 'questions',
    'skills_arena.all_tests': 'All Tests',
    'skills_arena.available': 'available',
    'skills_arena.tests_label': 'Tests',
    'skills_arena.streak_label': 'Day Streak',
    'skills_arena.best_score': 'Best score',
    'skills_arena.no_tests_in_category': 'No tests in this category',
    'skills_arena.badges': 'Badges',
    // Skills Arena Resources
    'skills_arena.resources_title': 'Educational Resources',
    'skills_arena.resources_description': 'Tools and materials to boost your development',
    'skills_arena.resources_count': 'resources',
    'skills_arena.resource_type': 'Resource',
    'skills_arena.open_resource': 'Open resource',
    // Skills Arena Categories
    'skills_arena.category.all': 'All',
    'skills_arena.category.self_knowledge': 'Self-Knowledge',
    'skills_arena.category.communication': 'Communication',
    'skills_arena.category.balance': 'Balance',
    'skills_arena.category.leadership': 'Leadership',
    'skills_arena.category.emotional': 'Emotional Intelligence',
    // Skills Arena Difficulties
    'skills_arena.difficulty.beginner': 'Beginner',
    'skills_arena.difficulty.intermediate': 'Intermediate',
    'skills_arena.difficulty.advanced': 'Advanced',
    // Skills Arena Tests
    'skills_arena.tests.personal_brand.title': 'Personal Brand',
    'skills_arena.tests.personal_brand.description': 'Discover your essence and build an authentic professional identity',
    'skills_arena.tests.wheel_of_life.title': 'Wheel of Life',
    'skills_arena.tests.wheel_of_life.description': 'Evaluate the balance in different areas of your life',
    'skills_arena.tests.active_listening.title': 'Active Listening',
    'skills_arena.tests.active_listening.description': 'Measure your ability to listen and understand others',
    'skills_arena.tests.empathy_quotient.title': 'Empathy Quotient',
    'skills_arena.tests.empathy_quotient.description': 'Discover your level of empathy and emotional connection',
    'skills_arena.tests.leadership_style.title': 'Leadership Style',
    'skills_arena.tests.leadership_style.description': 'Identify your natural leadership style',
    'skills_arena.tests.conflict_resolution.title': 'Conflict Resolution',
    'skills_arena.tests.conflict_resolution.description': 'Evaluate your ability to handle and resolve conflicts',

    // Wheel of Life
    'wheel_of_life.title': 'Wheel of Life',
    'wheel_of_life.intro_description': 'Evaluate 12 key areas of your life. Identify your strengths, weaknesses, and the biggest gaps between your current and desired situation.',
    'wheel_of_life.areas_count': 'life areas',
    'wheel_of_life.start': 'Start',
    'wheel_of_life.start_new': 'Start over',
    'wheel_of_life.continue_progress': 'Continue where I left off',
    'wheel_of_life.current_score': 'Current score',
    'wheel_of_life.desired_score': 'Desired score',
    'wheel_of_life.score_low': 'Very low',
    'wheel_of_life.score_high': 'Excellent',
    'wheel_of_life.reason_label': 'Why this score?',
    'wheel_of_life.reason_placeholder': 'Optional: briefly describe your situation in this area...',
    'wheel_of_life.optional': 'optional',
    'wheel_of_life.next': 'Next',
    'wheel_of_life.previous': 'Previous',
    'wheel_of_life.review': 'Review',
    'wheel_of_life.edit': 'Edit',
    'wheel_of_life.submit': 'Submit results',
    'wheel_of_life.submitting': 'Submitting...',
    'wheel_of_life.review_title': 'Review your answers',
    'wheel_of_life.review_description': 'Tap any area to edit it before submitting',
    'wheel_of_life.current': 'Current',
    'wheel_of_life.desired': 'Desired',
    'wheel_of_life.gap': 'Gap',
    'wheel_of_life.results_title': 'Your Results',
    'wheel_of_life.balance_score': 'Balance Score',
    'wheel_of_life.avg_current': 'avg. current',
    'wheel_of_life.avg_desired': 'avg. desired',
    'wheel_of_life.your_wheel': 'Your Wheel of Life',
    'wheel_of_life.strengths': 'Your Strengths',
    'wheel_of_life.weaknesses': 'Areas for Improvement',
    'wheel_of_life.biggest_gaps': 'Biggest Gaps',
    'wheel_of_life.recommendations': 'Recommendations',
    'wheel_of_life.back_to_arena': 'Back to Arena',
    'wheel_of_life.play_again': 'Play again',
    'wheel_of_life.first_attempt_bonus': 'First attempt bonus!',
    'wheel_of_life.total_xp': 'Total XP',
    // Wheel of Life - Areas
    'wheel_of_life.area.trabajo': 'Work',
    'wheel_of_life.area.dinero': 'Money',
    'wheel_of_life.area.salud': 'Health',
    'wheel_of_life.area.amor': 'Love',
    'wheel_of_life.area.crecimiento_personal': 'Personal Growth',
    'wheel_of_life.area.diversion': 'Fun',
    'wheel_of_life.area.entorno_fisico': 'Physical Environment',
    'wheel_of_life.area.espiritualidad': 'Spirituality',
    'wheel_of_life.area.amigos': 'Friends',
    'wheel_of_life.area.familia': 'Family',
    'wheel_of_life.area.alimentacion': 'Nutrition',
    'wheel_of_life.area.ejercicio_fisico': 'Physical Exercise',
    // Wheel of Life - Area Descriptions
    'wheel_of_life.area_desc.trabajo': 'How satisfied are you with your career and current work?',
    'wheel_of_life.area_desc.dinero': 'How do you feel about your financial situation?',
    'wheel_of_life.area_desc.salud': 'How is your overall physical and mental health?',
    'wheel_of_life.area_desc.amor': 'How is your romantic life and relationships?',
    'wheel_of_life.area_desc.crecimiento_personal': 'Are you constantly growing and learning?',
    'wheel_of_life.area_desc.diversion': 'Do you dedicate enough time to fun and leisure?',
    'wheel_of_life.area_desc.entorno_fisico': 'Does your home and environment make you feel comfortable?',
    'wheel_of_life.area_desc.espiritualidad': 'Do you have inner peace and spiritual connection?',
    'wheel_of_life.area_desc.amigos': 'How is the quality of your friendships?',
    'wheel_of_life.area_desc.familia': 'How is your relationship with your family?',
    'wheel_of_life.area_desc.alimentacion': 'How are your eating habits and nutrition?',
    'wheel_of_life.area_desc.ejercicio_fisico': 'Do you exercise regularly?',
    // Wheel of Life - Recommendations
    'wheel_of_life.recommendation.trabajo': 'Reflect on what truly excites you in your career. Consider talking to a mentor or exploring new professional development opportunities.',
    'wheel_of_life.recommendation.dinero': 'Create a monthly budget and set short and long-term financial goals. Consider seeking financial advice.',
    'wheel_of_life.recommendation.salud': 'Prioritize your well-being with regular check-ups, stress management, and good sleep habits.',
    'wheel_of_life.recommendation.amor': 'Invest quality time in your relationships. Open communication and vulnerability are key.',
    'wheel_of_life.recommendation.crecimiento_personal': 'Establish a daily learning habit: reading, courses, or new experiences that challenge you.',
    'wheel_of_life.recommendation.diversion': 'Schedule time for activities you enjoy. Leisure is essential for creativity and well-being.',
    'wheel_of_life.recommendation.entorno_fisico': 'Dedicate time to organizing and improving your space. An orderly environment positively impacts your mind.',
    'wheel_of_life.recommendation.espiritualidad': 'Explore meditation, mindfulness, or any activity that connects you with your purpose.',
    'wheel_of_life.recommendation.amigos': 'Actively cultivate your friendships. Plan regular get-togethers and be intentional with your connections.',
    'wheel_of_life.recommendation.familia': 'Strengthen family bonds with regular communication and quality time together.',
    'wheel_of_life.recommendation.alimentacion': 'Adopt more mindful eating. Plan your meals and increase your fruit and vegetable intake.',
    'wheel_of_life.recommendation.ejercicio_fisico': 'Start with 30 minutes of physical activity 3 times a week. Find an activity you enjoy.',

    // Gamified Dashboard
    'nav.gamified_dashboard': 'Gamified Dashboard',
    'nav.desc.gamified_dashboard': 'Your progress with mountain, achievements and ranking',
    'nav.gamified_dashboard_v2': 'Dashboard V2',
    'nav.desc.gamified_dashboard_v2': 'New version with radar, badges and activity',
    'nav.team_dashboard': 'Team Dashboard',
    'nav.desc.team_dashboard': 'Team performance and metrics for leaders',
    'gamified.mountain_title': 'Fire Mountain',
    'gamified.streak_days': 'Day Streak',
    'gamified.yesterday': 'YESTERDAY',
    'gamified.today': 'TODAY',
    'gamified.daily_climb': 'Daily Climb',
    'gamified.rewards': 'Rewards',
    'gamified.filler_words': 'Filler Words',
    'gamified.ranking': 'Ranking',
    'gamified.feedback': 'Feedback',
    'gamified.insight': 'Insight',
    'gamified.progress_listen': 'Listen',
    'gamified.progress_security': 'Security',
    'gamified.progress_speak': 'Speak',

    // Omi Admin Insights
    'omi_insights.title': 'Omi Platform Insights',
    'omi_insights.description': 'Platform-wide conversation analytics and scalability projections',
    'omi_insights.error_title': 'Error',
    'omi_insights.error_loading': 'Error loading Omi insights',
    'omi_insights.total_conversations': 'Total Conversations',
    'omi_insights.segments': 'segments',
    'omi_insights.active_users': 'Active Users',
    'omi_insights.of_total': 'of total',
    'omi_insights.avg_per_user': 'Average per User',
    'omi_insights.median': 'Median',
    'omi_insights.with_feedback': 'With Feedback',
    'omi_insights.analyzed': 'analyzed',
    'omi_insights.avg_duration': 'Average Duration',
    'omi_insights.words_avg': 'words average',
    'omi_insights.avg_segments': 'Average Segments',
    'omi_insights.per_transcript': 'per transcript',
    'omi_insights.avg_score': 'Average Score',
    'omi_insights.communication_quality': 'Communication quality',
    'omi_insights.scalability_title': 'Scalability to 600 users',
    'omi_insights.scalability_description': 'Storage projection for {users} users',
    'omi_insights.current_storage': 'Current Storage',
    'omi_insights.per_user': 'user',
    'omi_insights.projected_storage': 'Projection',
    'omi_insights.for_users': 'for {users} users',
    'omi_insights.tier_usage': 'Tier usage',
    'omi_insights.of': 'of',
    'omi_insights.recommended_tier': 'Recommended tier',
    'omi_insights.tier_comfortable': 'Comfortable capacity for projected growth',
    'omi_insights.tier_adequate': 'Adequate capacity, monitor growth',
    'omi_insights.tier_tight': 'Tight capacity, consider upgrade',
    'omi_insights.growth_title': 'Growth Trends',
    'omi_insights.growth_description': 'Recent conversation activity',
    'omi_insights.last_7_days': 'Last 7 days',
    'omi_insights.last_30_days': 'Last 30 days',
    'omi_insights.per_day': 'day',
    'omi_insights.growth_rate': 'Growth Rate',
    'omi_insights.vs_30_day_avg': 'vs 30-day avg',
  }
};

/* eslint-disable-next-line react-refresh/only-export-components */
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

/* eslint-disable-next-line react-refresh/only-export-components */
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};


