import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Navigation
    'nav.features': 'Características',
    'nav.success_cases': 'Casos de Éxito',
    'nav.login': 'Iniciar Sesión',
    'nav.start_free': 'Empezar Gratis',
    'nav.navigation': 'Navegación',
    'nav.logout': 'Cerrar Sesión',
    
    // Hero Section
    'hero.badge': 'IA · Mentoría · Crecimiento Diario',
    'hero.title_part1': 'no te entrena para un curso.',
    'hero.title_part2': 'Te transforma para siempre.',
    'hero.description': 'Tu mentora de inteligencia artificial que impulsa la evolución y el crecimiento diario de equipos en el sector de TI. Una experiencia retadora, emocionalmente inteligente y visionaria.',
    'hero.start_evolution': 'Comenzar tu Evolución',
    'hero.watch_demo': 'Ver Demo',
    
    // Features Section
    'features.title': '¿Cómo funciona',
    'features.description': 'Una plataforma completa que combina inteligencia artificial, gamificación y mentoría personalizada para acelerar el crecimiento de tu equipo.',
    'features.dashboard.title': 'Dashboard Personalizado',
    'features.dashboard.description': 'Visualiza métricas de progreso, sesiones completadas y racha de días activos en tiempo real.',
    'features.workplan.title': 'Plan de Trabajo Visual',
    'features.workplan.description': 'Rutas de aprendizaje personalizadas con módulos y objetivos claros en formato interactivo.',
    'features.achievements.title': 'Sistema de Logros',
    'features.achievements.description': 'Insignias, XP y leaderboards que motivan la constancia y celebran cada hito alcanzado.',
    'features.calendar.title': 'Calendario Inteligente',
    'features.calendar.description': 'Sesiones de mentoría sincronizadas con Google Calendar y Outlook para una organización perfecta.',
    
    // Benefits Section
    'benefits.title': 'Más que una herramienta, un compañero de crecimiento',
    'benefits.description': 'no es solo tecnología. Es una experiencia diseñada para crear conexiones humanas auténticas mientras potencia el desarrollo profesional de cada miembro de tu equipo.',
    'benefits.mentoring': 'Mentoría personalizada basada en IA avanzada',
    'benefits.integration': 'Integración perfecta con herramientas existentes',
    'benefits.automation': 'Automatización inteligente de flujos de trabajo',
    'benefits.metrics': 'Métricas claras de progreso y ROI',
    'benefits.humanity.title': 'Humanidad Aumentada',
    'benefits.humanity.description': 'Tecnología que potencia la conexión humana, no que la reemplaza. Cada interacción está diseñada para ser auténtica, retadora y transformadora.',
    
    // Testimonials
    'testimonials.title': 'Lo que dicen nuestros usuarios',
    'testimonials.subtitle': 'Líderes de TI que ya están transformando sus equipos con',
    'testimonials.carlos.content': 'La plataforma ha revolucionado cómo desarrollamos talento en nuestro equipo. Los resultados son medibles y el engagement ha aumentado un 300%.',
    'testimonials.ana.content': 'La gamificación realmente funciona. Nuestros desarrolladores están más motivados y las habilidades blandas han mejorado significativamente.',
    'testimonials.roberto.content': 'La automatización de la plataforma nos ahorra 10 horas semanales en gestión de equipo, permitiéndonos enfocarnos en lo que realmente importa.',
    
    // CTA Section
    'cta.title': '¿Listo para transformar tu equipo?',
    'cta.description': '�snete a cientos de líderes de TI que ya están viendo resultados reales. Comienza tu prueba gratuita hoy y descubre el potencial de tu equipo.',
    'cta.start_trial': 'Iniciar Prueba Gratuita',
    'cta.schedule_demo': 'Agendar Demo',
    
    // Footer
    'footer.copyright': 'Transformando el futuro del aprendizaje en TI.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Cargando dashboard...',
    'dashboard.home': 'Dashboard',
    'dashboard.org.title': 'Dashboard de Mi Organización',
    'dashboard.org.description': 'Vista de tu equipo y progreso organizacional',
    // Dashboard User
    'dashboard.user.title': 'My Dashboard',
    'dashboard.user.greeting': 'Hello',
    'dashboard.user.user': 'User',
    'dashboard.user.description': 'Here is your personal coaching progress',
    'dashboard.user.radar_title': '360° Competency Assessment',
    'dashboard.user.radar_description': 'Comparison between your self-assessment and your coach\'s assessment',
    'dashboard.user.my_sessions': 'My Sessions',
    'dashboard.user.upcoming': 'Upcoming',
    'dashboard.user.consistency': 'My Consistency',
    'dashboard.user.wellbeing': 'My Wellbeing',
    'dashboard.user.sessions_completed': 'Sessions completed',
    'dashboard.user.sessions_scheduled': 'Scheduled sessions',
    'dashboard.user.attendance_rate': 'Attendance rate',
    'dashboard.user.average_mood': 'Average mood',
    'dashboard.user.monthly_progress': 'My Monthly Progress',
    'dashboard.user.monthly_description': 'Your evolution in recent months',
    'dashboard.user.sessions_status': 'My Sessions',
    'dashboard.user.status_description': 'Status of your sessions',
    'dashboard.user.weekly_activity': 'My Weekly Activity',
    'dashboard.user.weekly_description': 'Tus sesiones en la última semana',
    'dashboard.user.clarity': 'Claridad (C)',
    'dashboard.user.structure': 'Estructura (E)',  
    'dashboard.user.emotional_alignment': 'Alineación Emocional (A)',
    'dashboard.user.action_influence': 'Acción e Influencia (I)',
    'dashboard.user.my_evaluation': 'Mi Evaluación',
    'dashboard.user.coach_evaluation': 'Evaluación Coach',
    'dashboard.charts.monthly_performance': 'Rendimiento Mensual del Equipo',
    'dashboard.charts.monthly_description': 'Progreso de tu organización por mes',
    'dashboard.charts.team_sessions': 'Sesiones del Equipo',
    'dashboard.charts.completed': 'Completadas',
    'dashboard.charts.team_status': 'Estado del Equipo',
    'dashboard.charts.status_description': 'Distribución de sesiones',
    'dashboard.charts.weekly_activity': 'Actividad Semanal del Equipo',
    'dashboard.charts.weekly_description': 'Sesiones diarias de tu organización',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.coach': 'Coach',
    'nav.roleplay': 'Sala de entrenamiento',
    'nav.first_interview': 'Mi Primera Entrevista',
    'nav.interview_history': 'Historial de Entrevistas',
    'nav.demo': 'Demo',
    'nav.demo_training': 'Demo Entrenamiento',
    'nav.roleplay_progress': 'Mi Progreso',
    'nav.learning_path': 'Ruta de Aprendizaje',
    'nav.team_learning_progress': 'Progreso del Equipo',
    'nav.sessions': 'Historial',
    'nav.analytics': 'Analytics',
    'nav.organizations': 'Organizaciones',
    'nav.users': 'Usuarios',
    'nav.reports': 'Reports',
    'nav.trends': 'Trends',
    'nav.plans': 'Planes',
    'nav.documents': 'Documentos',
    'nav.settings': 'Ajustes',
    'nav.my_team': 'Mi Equipo',
    'nav.plan': 'Plan',
    'nav.achievements': 'Logros',
    'dashboard.analytics': 'Analytics',
    'dashboard.reports': 'Reports',
    'dashboard.trends': 'Trends',
    'dashboard.users': 'Usuarios',
    'dashboard.plans': 'Planes',
    'dashboard.settings': 'Settings',
    'dashboard.team.title': 'Mi Equipo',
    'dashboard.team.description': 'Gestiona y administra los miembros de tu equipo',
    'dashboard.team.upload_csv': 'Cargar Usuarios desde CSV',
    'dashboard.team.upload_description': 'Importa múltiples usuarios a tu equipo utilizando un archivo CSV',
    'dashboard.team.download_template': 'Descargar Plantilla',
    'dashboard.team.processing': 'Procesando archivo CSV...',
    'dashboard.team.results_title': 'Resultados de la Carga',
    'dashboard.team.successful': 'Exitosos',
    'dashboard.team.failed': 'Fallidos',
    'dashboard.team.total': 'Total',
    'dashboard.team.errors': 'Errores',
    'dashboard.team.format_required': 'Formato requerido',
    'dashboard.team.members': 'Miembros del Equipo',
    'dashboard.team.members_description': 'Lista de todos los miembros de tu equipo y su estado actual',
    'dashboard.team.name': 'Nombre',
    'dashboard.team.email': 'Email',
    'dashboard.team.role': 'Rol',
    'dashboard.team.status': 'Estado',
    'dashboard.team.join_date': 'Fecha de Ingreso',
    'dashboard.team.status_active': 'Activo',
    'dashboard.team.status_pending': 'Pendiente',
    'dashboard.team.status_suspended': 'Suspendido',
    'dashboard.team.upload_success': 'Carga completada',
    'dashboard.team.upload_error': 'Error en la carga',
    'dashboard.team.template_downloaded': 'Plantilla descargada',
    'dashboard.team.csv_error': 'Por favor selecciona un archivo CSV válido',

    // Coach
    'coach.title': 'Coach IA',
    'coach.subtitle': 'Tu mentor personal para crecimiento profesional',
    'coach.ai_coach': 'Coach de Inteligencia Artificial',
    'coach.description': 'Conversa con tu coach personal powered by AI para obtener mentoría personalizada',
    'coach.status.ready': 'Listo para conversar',
    'coach.status.connecting': 'Conectando...',
    'coach.status.listening': 'Escuchando...',
    'coach.status.thinking': 'Procesando...',
    'coach.status.speaking': 'Respondiendo...',
    'coach.start_listening': 'Iniciar Conversación',
    'coach.stop_listening': 'Detener',
    'coach.mute': 'Silenciar',
    'coach.unmute': 'Activar Audio',
    'coach.instructions': 'Escribe tu consulta y obtén coaching personalizado en tiempo real',
    'coach.error.no_api_key': 'Modo demo - La integración completa de voz requiere configuración',
    'coach.new_conversation': 'Nueva Conversación',
    'coach.voice_mode': 'Modo Voz (Próximamente)',
    'coach.placeholder': 'Escribe tu consulta de coaching...',
    'coach.thinking': 'Tu coach está pensando...',
    'coach.specialties': 'Tu coach inteligente está listo para ayudarte con liderazgo, productividad y desarrollo profesional',

    // AI Resources
    'nav.ai_resources': 'Recursos Educativos IA',
    'ai_resources.title': 'Recursos Educativos IA',
    'ai_resources.description': 'Recursos de inteligencia artificial para capacitación',
    'ai_resources.open_resource': 'Abrir Recurso',
    'ai_resources.add_resource': 'Agregar Recurso',
    'ai_resources.add_title': 'Nuevo Recurso Educativo',
    'ai_resources.form.title': 'Título',
    'ai_resources.form.title_placeholder': 'Nombre del recurso',
    'ai_resources.form.description': 'Descripción',
    'ai_resources.form.description_placeholder': 'Breve descripción del recurso',
    'ai_resources.form.url': 'URL del Recurso',
    'ai_resources.form.url_placeholder': 'https://ejemplo.com',
    'ai_resources.form.icon': 'Icono',
    'ai_resources.form.color': 'Color',
    'ai_resources.form.submit': 'Guardar Recurso',
    'ai_resources.form.cancel': 'Cancelar',
    'ai_resources.success': 'Recurso agregado correctamente',
    'ai_resources.error': 'Error al agregar recurso',
    'ai_resources.loading': 'Cargando recursos...',
    'ai_resources.empty': 'No hay recursos disponibles',

    // Avatar Showcase
    'nav.avatar_showcase': 'Comparativa Avatares',
    'avatar_showcase.title': 'Comparativa de Avatares Voxel',
    'avatar_showcase.description': 'Compara diferentes enfoques para renderizar avatares 3D estilo voxel',

    // Navigation - Additional items
    'nav.avatar': 'Mi Avatar',
    'nav.stats': 'Mis Estadísticas',
    'nav.agent_config': 'Configuración Agentes',
    'nav.welcome': 'Hola',
    'nav.welcome_subtitle': '¿Qué quieres hacer hoy?',

    // Navigation - Card descriptions
    'nav.desc.dashboard': 'Tu página de inicio',
    'nav.desc.avatar': 'Personaliza tu avatar 3D',
    'nav.desc.stats': 'Métricas y gráficos de tu progreso',
    'nav.desc.first_interview': 'Entrevista inicial estructurada',
    'nav.desc.roleplay': 'Practica escenarios con IA',
    'nav.desc.learning_path': 'Tu camino de desarrollo',
    'nav.desc.progress': 'Ve tu avance y métricas',
    'nav.desc.sessions': 'Historial de sesiones',
    'nav.desc.team_progress': 'Progreso de tu equipo',
    'nav.desc.my_team': 'Gestiona tu equipo',
    'nav.desc.plans': 'Planes de suscripción',
    'nav.desc.documents': 'Documentos del equipo',
    'nav.desc.settings': 'Configuración de cuenta',
    'nav.desc.coach': 'Conversación con tu coach IA',
    'nav.desc.agent_config': 'Configura perfiles y escenarios',
    'nav.desc.ai_resources': 'Recursos educativos de IA',
    'nav.desc.avatar_showcase': 'Galería de avatares',
    'nav.desc.demo': 'Prueba la plataforma',
    'nav.desc.demo_training': 'Entrenamiento de demostración',
    'nav.desc.analytics': 'Métricas de la plataforma',
    'nav.desc.organizations': 'Gestiona organizaciones',
    'nav.desc.users': 'Administra usuarios',
    'nav.desc.reports': 'Reportes detallados',
    'nav.desc.trends': 'Tendencias y patrones',
    'nav.desc.tech_week': 'Evento especial Tech Week',
    'nav.desc.interview_history': 'Historial de entrevistas',
    'nav.desc.hero_journey': 'Visualiza tu camino como una montaña',
    'nav.hero_journey': "Hero's Journey",
    'nav.omi_conversations': 'Mis Conversaciones',
    'nav.desc.omi_conversations': 'Grabaciones y análisis de Omi',

    // Navigation - Section headers
    'nav.section.profile': 'Mi Perfil',
    'nav.section.profile_desc': 'Tu información personal',
    'nav.section.practice': 'Práctica',
    'nav.section.practice_desc': 'Mejora tus habilidades de comunicación',
    'nav.section.progress': 'Mi Progreso',
    'nav.section.progress_desc': 'Revisa tu avance y resultados',
    'nav.section.team': 'Mi Equipo',
    'nav.section.team_desc': 'Gestión y seguimiento del equipo',
    'nav.section.config': 'Configuración',
    'nav.section.config_desc': 'Ajustes y documentos',
    'nav.section.admin': 'Administración',
    'nav.section.admin_desc': 'Herramientas de administrador',

    // Roles
    'roles.admin': 'Administrador Global',
    'roles.manager': 'Administrador',
    'roles.user': 'Usuario',
    'roles.default_user': 'Usuario',

    // Omi Conversations
    'omi.page_description': 'Revisa tus conversaciones grabadas y su análisis',
    'omi.error_loading': 'Error al cargar las conversaciones',
    'omi.no_conversations': 'No hay conversaciones',
    'omi.no_conversations_desc': 'Tus conversaciones grabadas con Omi aparecerán aquí',
    'omi.communication_analysis': 'Análisis de Comunicación',
    'omi.overall_score': 'Puntuación General',
    'omi.clarity': 'Claridad',
    'omi.engagement': 'Engagement',
    'omi.structure': 'Estructura',
    'omi.strengths': 'Fortalezas',
    'omi.areas_to_improve': 'Áreas de Mejora',
    'omi.insights': 'Insights de Comunicación',
    'omi.objections': 'Manejo de Objeciones',
    'omi.calls_to_action': 'Llamados a Acción',
    'omi.action_items': 'Acciones Pendientes',
    'omi.events': 'Eventos',
    'omi.transcript': 'Transcripción',
    'omi.no_transcript': 'No hay transcripción disponible',
    'common.back': 'Volver',

    // Dashboard - Omi Stats Section
    'dashboard.user.omi_section': 'Mis Conversaciones Omi',
    'dashboard.user.omi_description': 'Análisis de tus conversaciones grabadas',
    'dashboard.user.omi_avg_scores': 'Puntuaciones Promedio',
    'dashboard.user.omi_evolution': 'Evolución de Puntuación',
    'dashboard.user.omi_total_conversations': 'Conversaciones',
    'dashboard.user.omi_avg_score': 'Puntuación Promedio',
    'dashboard.user.omi_total_time': 'Tiempo Total',
    'dashboard.user.omi_no_data': 'Sin datos de conversaciones',
    'dashboard.user.omi_no_data_desc': 'Graba conversaciones con Omi para ver tu análisis aquí',
    'dashboard.user.omi_overall': 'General',

    // SVG Converter
    'nav.svg_converter': 'Convertidor SVG',
    'nav.desc.svg_converter': 'Convierte imágenes a SVG y gestiona assets',
    'svg_converter.title': 'Convertidor SVG',
    'svg_converter.description': 'Convierte imágenes a vectores y gestiona tu galería de assets',
    'svg_converter.tab_convert': 'Convertir',
    'svg_converter.tab_gallery': 'Galería',
    'svg_converter.drag_drop_or_click': 'Arrastra una imagen o haz clic para seleccionar',
    'svg_converter.drop_here': 'Suelta la imagen aquí',
    'svg_converter.supported_formats': 'Formatos soportados: JPG, PNG, WebP',
    'svg_converter.max_file_size': 'Tamaño máximo: 5MB',
    'svg_converter.error_invalid_format': 'Formato de archivo no válido. Usa JPG, PNG o WebP.',
    'svg_converter.error_file_too_large': 'El archivo es demasiado grande. Máximo 5MB.',
    'svg_converter.settings_title': 'Configuración',
    'svg_converter.preset_label': 'Tipo de imagen',
    'svg_converter.preset_photo': 'Fotografía',
    'svg_converter.preset_logo': 'Logo',
    'svg_converter.preset_illustration': 'Ilustración',
    'svg_converter.preset_line_art': 'Line Art',
    'svg_converter.color_count_label': 'Cantidad de colores',
    'svg_converter.color_count_hint': 'Menos colores = archivo más pequeño',
    'svg_converter.original': 'Original',
    'svg_converter.converted': 'SVG Convertido',
    'svg_converter.converting': 'Convirtiendo...',
    'svg_converter.no_preview': 'Sin vista previa',
    'svg_converter.error_conversion_failed': 'Error al convertir la imagen',
    'svg_converter.warning_large_svg': 'El SVG generado es grande ({size} KB). Considera reducir los colores.',
    'svg_converter.reset': 'Nueva imagen',
    'svg_converter.download': 'Descargar',
    'svg_converter.save_to_gallery': 'Guardar en galería',
    'svg_converter.save_dialog_title': 'Guardar asset',
    'svg_converter.save_dialog_description': 'Añade información para guardar este SVG en la galería',
    'svg_converter.field_name': 'Nombre',
    'svg_converter.field_name_placeholder': 'Nombre del asset',
    'svg_converter.field_description': 'Descripción',
    'svg_converter.field_description_placeholder': 'Descripción opcional',
    'svg_converter.field_category': 'Categoría',
    'svg_converter.field_tags': 'Etiquetas',
    'svg_converter.field_tags_placeholder': 'logo, icono, banner',
    'svg_converter.field_tags_hint': 'Separadas por coma',
    'svg_converter.category_general': 'General',
    'svg_converter.category_icons': 'Iconos',
    'svg_converter.category_illustrations': 'Ilustraciones',
    'svg_converter.category_logos': 'Logos',
    'svg_converter.category_backgrounds': 'Fondos',
    'svg_converter.category_patterns': 'Patrones',
    'svg_converter.save': 'Guardar',
    'svg_converter.success': 'Éxito',
    'svg_converter.error': 'Error',
    'svg_converter.error_name_required': 'El nombre es requerido',
    'svg_converter.error_save_failed': 'Error al guardar el asset',
    'svg_converter.asset_saved': 'Asset guardado correctamente',
    'svg_converter.search_placeholder': 'Buscar assets...',
    'svg_converter.all_categories': 'Todas las categorías',
    'svg_converter.loading': 'Cargando...',
    'svg_converter.error_loading': 'Error al cargar los assets',
    'svg_converter.no_assets': 'No hay assets',
    'svg_converter.no_assets_hint': 'Convierte una imagen para crear tu primer asset',
    'svg_converter.inactive': 'Inactivo',
    'svg_converter.active': 'Activo',
    'svg_converter.asset_details': 'Detalles del asset',
    'svg_converter.asset_details_description': 'Información y acciones del asset',
    'svg_converter.edit_asset': 'Editar asset',
    'svg_converter.edit_asset_description': 'Modifica la información del asset',
    'svg_converter.edit': 'Editar',
    'svg_converter.delete': 'Eliminar',
    'svg_converter.copy_svg': 'Copiar SVG',
    'svg_converter.copied': 'Copiado',
    'svg_converter.error_copy_failed': 'Error al copiar',
    'svg_converter.activate': 'Activar',
    'svg_converter.deactivate': 'Desactivar',
    'svg_converter.asset_updated': 'Asset actualizado',
    'svg_converter.asset_activated': 'Asset activado',
    'svg_converter.asset_deactivated': 'Asset desactivado',
    'svg_converter.error_update_failed': 'Error al actualizar',
    'svg_converter.delete_confirm_title': '¿Eliminar asset?',
    'svg_converter.delete_confirm_description': 'Esta acción desactivará el asset. Podrás reactivarlo más tarde.',
    'svg_converter.asset_deleted': 'Asset eliminado',
    'svg_converter.error_delete_failed': 'Error al eliminar',
  },
  en: {
    // Navigation
    'nav.features': 'Features',
    'nav.success_cases': 'Success Cases',
    'nav.login': 'Login',
    'nav.start_free': 'Start Free',
    'nav.navigation': 'Navigation',
    'nav.logout': 'Logout',
    'nav.first_interview': 'My First Interview',
    'nav.interview_history': 'Interview History',
    
    // Hero Section
    'hero.badge': 'AI · Mentoring · Daily Growth',
    'hero.title_part1': 'doesn\'t train you for a course.',
    'hero.title_part2': 'It transforms you forever.',
    'hero.description': 'Your artificial intelligence mentor that drives the evolution and daily growth of IT teams. A challenging, emotionally intelligent and visionary experience.',
    'hero.start_evolution': 'Start Your Evolution',
    'hero.watch_demo': 'Watch Demo',
    
    // Features Section
    'features.title': 'How does',
    'features.description': 'A complete platform that combines artificial intelligence, gamification and personalized mentoring to accelerate your team\'s growth.',
    'features.dashboard.title': 'Personalized Dashboard',
    'features.dashboard.description': 'Visualize progress metrics, completed sessions and active day streaks in real time.',
    'features.workplan.title': 'Visual Work Plan',
    'features.workplan.description': 'Personalized learning paths with clear modules and objectives in interactive format.',
    'features.achievements.title': 'Achievement System',
    'features.achievements.description': 'Badges, XP and leaderboards that motivate consistency and celebrate every milestone achieved.',
    'features.calendar.title': 'Smart Calendar',
    'features.calendar.description': 'Mentoring sessions synchronized with Google Calendar and Outlook for perfect organization.',
    
    // Benefits Section
    'benefits.title': 'More than a tool, a growth companion',
    'benefits.description': 'is not just technology. It\'s an experience designed to create authentic human connections while enhancing the professional development of each team member.',
    'benefits.mentoring': 'Personalized mentoring based on advanced AI',
    'benefits.integration': 'Perfect integration with existing tools',
    'benefits.automation': 'Intelligent workflow automation',
    'benefits.metrics': 'Clear progress and ROI metrics',
    'benefits.humanity.title': 'Augmented Humanity',
    'benefits.humanity.description': 'Technology that enhances human connection, doesn\'t replace it. Every interaction is designed to be authentic, challenging and transformative.',
    
    // Testimonials
    'testimonials.title': 'What our users say',
    'testimonials.subtitle': 'IT leaders who are already transforming their teams with',
    'testimonials.carlos.content': 'The platform has revolutionized how we develop talent in our team. Results are measurable and engagement has increased by 300%.',
    'testimonials.ana.content': 'Gamification really works. Our developers are more motivated and soft skills have improved significantly.',
    'testimonials.roberto.content': 'The platform\'s automation saves us 10 hours weekly in team management, allowing us to focus on what really matters.',
    
    // CTA Section
    'cta.title': 'Ready to transform your team?',
    'cta.description': 'Join hundreds of IT leaders who are already seeing real results. Start your free trial today and discover your team\'s potential.',
    'cta.start_trial': 'Start Free Trial',
    'cta.schedule_demo': 'Schedule Demo',
    
    // Footer
    'footer.copyright': 'Transforming the future of IT learning.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.home': 'Dashboard',
    'dashboard.org.title': 'My Organization Dashboard',
    'dashboard.org.description': 'View your team and organizational progress',
    'dashboard.stats.team_sessions': 'Team Sessions',
    'dashboard.stats.organization_total': 'Organization total',
    'dashboard.stats.active': 'Active',
    'dashboard.stats.in_progress': 'In progress or scheduled',
    'dashboard.stats.performance': 'Performance',
    'dashboard.stats.completion_rate': 'Team completion rate',
    'dashboard.stats.team_wellbeing': 'Team Wellbeing',
    'dashboard.stats.average_mood': 'Average mood',
    'dashboard.charts.monthly_performance': 'Monthly Team Performance',
    'dashboard.charts.monthly_description': 'Your organization\'s progress by month',
    'dashboard.charts.team_sessions': 'Team Sessions',
    'dashboard.charts.completed': 'Completed',
    'dashboard.charts.team_status': 'Team Status',
    'dashboard.charts.status_description': 'Session distribution',
    'dashboard.charts.weekly_activity': 'Weekly Team Activity',
    'dashboard.charts.weekly_description': 'Daily sessions from your organization',
    
    // Dashboard User
    'dashboard.user.title': 'My Dashboard',
    'dashboard.user.greeting': 'Hello',
    'dashboard.user.user': 'User',
    'dashboard.user.description': 'Here is your personal coaching progress',
    'dashboard.user.radar_title': '360° Competency Assessment',
    'dashboard.user.radar_description': 'Comparison between your self-assessment and your coach\'s assessment',
    'dashboard.user.my_sessions': 'My Sessions',
    'dashboard.user.upcoming': 'Upcoming',
    'dashboard.user.consistency': 'My Consistency',
    'dashboard.user.wellbeing': 'My Wellbeing',
    'dashboard.user.sessions_completed': 'Sessions completed',
    'dashboard.user.sessions_scheduled': 'Scheduled sessions',
    'dashboard.user.attendance_rate': 'Attendance rate',
    'dashboard.user.average_mood': 'Average mood',
    'dashboard.user.monthly_progress': 'My Monthly Progress',
    'dashboard.user.monthly_description': 'Your evolution in recent months',
    'dashboard.user.sessions_status': 'My Sessions',
    'dashboard.user.status_description': 'Status of your sessions',
    'dashboard.user.weekly_activity': 'My Weekly Activity',
    'dashboard.user.weekly_description': 'Your sessions in the last week',
    'dashboard.user.clarity': 'Clarity (C)',
    'dashboard.user.structure': 'Structure (S)',  
    'dashboard.user.emotional_alignment': 'Emotional Alignment (A)',
    'dashboard.user.action_influence': 'Action & Influence (I)',
    'dashboard.user.my_evaluation': 'My Assessment',
    'dashboard.user.coach_evaluation': 'Coach Assessment',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.coach': 'Coach',
    'nav.roleplay': 'Training Room',
    'nav.demo': 'Demo',
    'nav.demo_training': 'Demo Training',
    'nav.roleplay_progress': 'Mi Progreso',
    'nav.learning_path': 'Learning Path',
    'nav.team_learning_progress': 'Team Progress',
    'nav.sessions': 'Historial',
    'nav.analytics': 'Analytics',
    'nav.organizations': 'Organizations',
    'nav.users': 'Users',
    'nav.reports': 'Reports',
    'nav.trends': 'Trends',
    'nav.plans': 'Plans',
    'nav.documents': 'Documents',
    'nav.settings': 'Settings',
    'nav.my_team': 'My Team',
    'nav.plan': 'Plan',
    'nav.achievements': 'Achievements',
    
    // Roles
    'roles.admin': 'Global Administrator',
    'roles.manager': 'Administrator',
    'roles.user': 'User',
    'roles.default_user': 'User',
    'dashboard.analytics': 'Analytics',
    'dashboard.reports': 'Reports',
    'dashboard.trends': 'Trends',
    'dashboard.users': 'Users',
    'dashboard.plans': 'Plans',
    'dashboard.settings': 'Settings',
    'dashboard.team.title': 'My Team',
    'dashboard.team.description': 'Manage and administer your team members',
    'dashboard.team.upload_csv': 'Upload Users from CSV',
    'dashboard.team.upload_description': 'Import multiple users to your team using a CSV file',
    'dashboard.team.download_template': 'Download Template',
    'dashboard.team.processing': 'Processing CSV file...',
    'dashboard.team.results_title': 'Upload Results',
    'dashboard.team.successful': 'Successful',
    'dashboard.team.failed': 'Failed',
    'dashboard.team.total': 'Total',
    'dashboard.team.errors': 'Errors',
    'dashboard.team.format_required': 'Required format',
    'dashboard.team.members': 'Team Members',
    'dashboard.team.members_description': 'List of all your team members and their current status',
    'dashboard.team.name': 'Name',
    'dashboard.team.email': 'Email',
    'dashboard.team.role': 'Role',
    'dashboard.team.status': 'Status',
    'dashboard.team.join_date': 'Join Date',
    'dashboard.team.status_active': 'Active',
    'dashboard.team.status_pending': 'Pending',
    'dashboard.team.status_suspended': 'Suspended',
    'dashboard.team.upload_success': 'Upload completed',
    'dashboard.team.upload_error': 'Upload error',
    'dashboard.team.template_downloaded': 'Template downloaded',
    'dashboard.team.csv_error': 'Please select a valid CSV file',

    // Coach
    'coach.title': 'AI Coach',
    'coach.subtitle': 'Your personal mentor for professional growth',
    'coach.ai_coach': 'Artificial Intelligence Coach',
    'coach.description': 'Chat with your AI-powered personal coach for personalized mentoring',
    'coach.status.ready': 'Ready to chat',
    'coach.status.connecting': 'Connecting...',
    'coach.status.listening': 'Listening...',
    'coach.status.thinking': 'Processing...',
    'coach.status.speaking': 'Responding...',
    'coach.start_listening': 'Start Conversation',
    'coach.stop_listening': 'Stop',
    'coach.mute': 'Mute',
    'coach.unmute': 'Unmute',
    'coach.instructions': 'Write your query and get personalized coaching in real time',
    'coach.error.no_api_key': 'Demo mode - Full voice integration requires configuration',
    'coach.new_conversation': 'New Conversation',
    'coach.voice_mode': 'Voice Mode (Coming Soon)',
    'coach.placeholder': 'Write your coaching query...',
    'coach.thinking': 'Your coach is thinking...',
    'coach.specialties': 'Your intelligent coach is ready to help you with leadership, productivity and professional development',

    // AI Resources
    'nav.ai_resources': 'AI Educational Resources',
    'ai_resources.title': 'AI Educational Resources',
    'ai_resources.description': 'Artificial intelligence resources for training',
    'ai_resources.open_resource': 'Open Resource',
    'ai_resources.add_resource': 'Add Resource',
    'ai_resources.add_title': 'New Educational Resource',
    'ai_resources.form.title': 'Title',
    'ai_resources.form.title_placeholder': 'Resource name',
    'ai_resources.form.description': 'Description',
    'ai_resources.form.description_placeholder': 'Brief description of the resource',
    'ai_resources.form.url': 'Resource URL',
    'ai_resources.form.url_placeholder': 'https://example.com',
    'ai_resources.form.icon': 'Icon',
    'ai_resources.form.color': 'Color',
    'ai_resources.form.submit': 'Save Resource',
    'ai_resources.form.cancel': 'Cancel',
    'ai_resources.success': 'Resource added successfully',
    'ai_resources.error': 'Error adding resource',
    'ai_resources.loading': 'Loading resources...',
    'ai_resources.empty': 'No resources available',

    // Avatar Showcase
    'nav.avatar_showcase': 'Avatar Showcase',
    'avatar_showcase.title': 'Voxel Avatar Showcase',
    'avatar_showcase.description': 'Compare different approaches for rendering 3D voxel-style avatars',

    // Navigation - Additional items
    'nav.avatar': 'My Avatar',
    'nav.stats': 'My Stats',
    'nav.agent_config': 'Agent Config',
    'nav.welcome': 'Hello',
    'nav.welcome_subtitle': 'What would you like to do today?',

    // Navigation - Card descriptions
    'nav.desc.dashboard': 'Your home page',
    'nav.desc.avatar': 'Customize your 3D avatar',
    'nav.desc.stats': 'Metrics and charts of your progress',
    'nav.desc.first_interview': 'Structured initial interview',
    'nav.desc.roleplay': 'Practice scenarios with AI',
    'nav.desc.learning_path': 'Your development path',
    'nav.desc.progress': 'View your progress and metrics',
    'nav.desc.sessions': 'Session history',
    'nav.desc.team_progress': 'Your team progress',
    'nav.desc.my_team': 'Manage your team',
    'nav.desc.plans': 'Subscription plans',
    'nav.desc.documents': 'Team documents',
    'nav.desc.settings': 'Account settings',
    'nav.desc.coach': 'Chat with your AI coach',
    'nav.desc.agent_config': 'Configure profiles and scenarios',
    'nav.desc.ai_resources': 'AI educational resources',
    'nav.desc.avatar_showcase': 'Avatar gallery',
    'nav.desc.demo': 'Try the platform',
    'nav.desc.demo_training': 'Demo training',
    'nav.desc.analytics': 'Platform metrics',
    'nav.desc.organizations': 'Manage organizations',
    'nav.desc.users': 'Manage users',
    'nav.desc.reports': 'Detailed reports',
    'nav.desc.trends': 'Trends and patterns',
    'nav.desc.tech_week': 'Tech Week special event',
    'nav.desc.interview_history': 'Interview history',
    'nav.desc.hero_journey': 'Visualize your path as a mountain',
    'nav.hero_journey': "Hero's Journey",
    'nav.omi_conversations': 'My Conversations',
    'nav.desc.omi_conversations': 'Omi recordings and analysis',

    // Navigation - Section headers
    'nav.section.profile': 'My Profile',
    'nav.section.profile_desc': 'Your personal information',
    'nav.section.practice': 'Practice',
    'nav.section.practice_desc': 'Improve your communication skills',
    'nav.section.progress': 'My Progress',
    'nav.section.progress_desc': 'Review your progress and results',
    'nav.section.team': 'My Team',
    'nav.section.team_desc': 'Team management and tracking',
    'nav.section.config': 'Settings',
    'nav.section.config_desc': 'Settings and documents',
    'nav.section.admin': 'Administration',
    'nav.section.admin_desc': 'Admin tools',

    // Omi Conversations
    'omi.page_description': 'Review your recorded conversations and analysis',
    'omi.error_loading': 'Error loading conversations',
    'omi.no_conversations': 'No conversations',
    'omi.no_conversations_desc': 'Your recorded Omi conversations will appear here',
    'omi.communication_analysis': 'Communication Analysis',
    'omi.overall_score': 'Overall Score',
    'omi.clarity': 'Clarity',
    'omi.engagement': 'Engagement',
    'omi.structure': 'Structure',
    'omi.strengths': 'Strengths',
    'omi.areas_to_improve': 'Areas to Improve',
    'omi.insights': 'Communication Insights',
    'omi.objections': 'Objection Handling',
    'omi.calls_to_action': 'Calls to Action',
    'omi.action_items': 'Action Items',
    'omi.events': 'Events',
    'omi.transcript': 'Transcript',
    'omi.no_transcript': 'No transcript available',
    'common.back': 'Back',

    // Dashboard - Omi Stats Section
    'dashboard.user.omi_section': 'My Omi Conversations',
    'dashboard.user.omi_description': 'Analysis of your recorded conversations',
    'dashboard.user.omi_avg_scores': 'Average Scores',
    'dashboard.user.omi_evolution': 'Score Evolution',
    'dashboard.user.omi_total_conversations': 'Conversations',
    'dashboard.user.omi_avg_score': 'Average Score',
    'dashboard.user.omi_total_time': 'Total Time',
    'dashboard.user.omi_no_data': 'No conversation data',
    'dashboard.user.omi_no_data_desc': 'Record conversations with Omi to see your analysis here',
    'dashboard.user.omi_overall': 'Overall',

    // SVG Converter
    'nav.svg_converter': 'SVG Converter',
    'nav.desc.svg_converter': 'Convert images to SVG and manage assets',
    'svg_converter.title': 'SVG Converter',
    'svg_converter.description': 'Convert images to vectors and manage your asset gallery',
    'svg_converter.tab_convert': 'Convert',
    'svg_converter.tab_gallery': 'Gallery',
    'svg_converter.drag_drop_or_click': 'Drag an image or click to select',
    'svg_converter.drop_here': 'Drop the image here',
    'svg_converter.supported_formats': 'Supported formats: JPG, PNG, WebP',
    'svg_converter.max_file_size': 'Max file size: 5MB',
    'svg_converter.error_invalid_format': 'Invalid file format. Use JPG, PNG or WebP.',
    'svg_converter.error_file_too_large': 'File is too large. Maximum 5MB.',
    'svg_converter.settings_title': 'Settings',
    'svg_converter.preset_label': 'Image type',
    'svg_converter.preset_photo': 'Photo',
    'svg_converter.preset_logo': 'Logo',
    'svg_converter.preset_illustration': 'Illustration',
    'svg_converter.preset_line_art': 'Line Art',
    'svg_converter.color_count_label': 'Color count',
    'svg_converter.color_count_hint': 'Fewer colors = smaller file',
    'svg_converter.original': 'Original',
    'svg_converter.converted': 'Converted SVG',
    'svg_converter.converting': 'Converting...',
    'svg_converter.no_preview': 'No preview',
    'svg_converter.error_conversion_failed': 'Error converting image',
    'svg_converter.warning_large_svg': 'Generated SVG is large ({size} KB). Consider reducing colors.',
    'svg_converter.reset': 'New image',
    'svg_converter.download': 'Download',
    'svg_converter.save_to_gallery': 'Save to gallery',
    'svg_converter.save_dialog_title': 'Save asset',
    'svg_converter.save_dialog_description': 'Add information to save this SVG to the gallery',
    'svg_converter.field_name': 'Name',
    'svg_converter.field_name_placeholder': 'Asset name',
    'svg_converter.field_description': 'Description',
    'svg_converter.field_description_placeholder': 'Optional description',
    'svg_converter.field_category': 'Category',
    'svg_converter.field_tags': 'Tags',
    'svg_converter.field_tags_placeholder': 'logo, icon, banner',
    'svg_converter.field_tags_hint': 'Comma separated',
    'svg_converter.category_general': 'General',
    'svg_converter.category_icons': 'Icons',
    'svg_converter.category_illustrations': 'Illustrations',
    'svg_converter.category_logos': 'Logos',
    'svg_converter.category_backgrounds': 'Backgrounds',
    'svg_converter.category_patterns': 'Patterns',
    'svg_converter.save': 'Save',
    'svg_converter.success': 'Success',
    'svg_converter.error': 'Error',
    'svg_converter.error_name_required': 'Name is required',
    'svg_converter.error_save_failed': 'Error saving asset',
    'svg_converter.asset_saved': 'Asset saved successfully',
    'svg_converter.search_placeholder': 'Search assets...',
    'svg_converter.all_categories': 'All categories',
    'svg_converter.loading': 'Loading...',
    'svg_converter.error_loading': 'Error loading assets',
    'svg_converter.no_assets': 'No assets',
    'svg_converter.no_assets_hint': 'Convert an image to create your first asset',
    'svg_converter.inactive': 'Inactive',
    'svg_converter.active': 'Active',
    'svg_converter.asset_details': 'Asset details',
    'svg_converter.asset_details_description': 'Asset information and actions',
    'svg_converter.edit_asset': 'Edit asset',
    'svg_converter.edit_asset_description': 'Modify asset information',
    'svg_converter.edit': 'Edit',
    'svg_converter.delete': 'Delete',
    'svg_converter.copy_svg': 'Copy SVG',
    'svg_converter.copied': 'Copied',
    'svg_converter.error_copy_failed': 'Error copying',
    'svg_converter.activate': 'Activate',
    'svg_converter.deactivate': 'Deactivate',
    'svg_converter.asset_updated': 'Asset updated',
    'svg_converter.asset_activated': 'Asset activated',
    'svg_converter.asset_deactivated': 'Asset deactivated',
    'svg_converter.error_update_failed': 'Error updating',
    'svg_converter.delete_confirm_title': 'Delete asset?',
    'svg_converter.delete_confirm_description': 'This action will deactivate the asset. You can reactivate it later.',
    'svg_converter.asset_deleted': 'Asset deleted',
    'svg_converter.error_delete_failed': 'Error deleting',
  }
};

/* eslint-disable-next-line react-refresh/only-export-components */
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

/* eslint-disable-next-line react-refresh/only-export-components */
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};


