export const SCENARIOS = [
  {
    icon: 'DollarSign',
    skill: 'Negociación',
    title: 'Cierre de venta con objeciones de precio',
    desc: 'El cliente dice que es muy caro. Practica cómo defender tu propuesta de valor sin ceder en precio.',
    color: 'text-pink-500',
    bg: 'bg-pink-500/10',
  },
  {
    icon: 'Users',
    skill: 'Liderazgo',
    title: 'Retroalimentación a un colaborador difícil',
    desc: 'Tu mejor talento tiene actitud negativa. Practica cómo dar feedback directo sin perder al empleado.',
    color: 'text-blue-500',
    bg: 'bg-blue-500/10',
  },
  {
    icon: 'Target',
    skill: 'Presentación',
    title: 'Pitch de producto ante directivos',
    desc: 'Tienes 5 minutos frente al comité. Practica cómo presentar resultados y pedir presupuesto con confianza.',
    color: 'text-green-500',
    bg: 'bg-green-500/10',
  },
  {
    icon: 'Shield',
    skill: 'Manejo de objeciones',
    title: 'Cliente que quiere cancelar el contrato',
    desc: 'Tu cliente más importante amenaza con irse. Practica retención con empatía y soluciones concretas.',
    color: 'text-yellow-500',
    bg: 'bg-yellow-500/10',
  },
  {
    icon: 'Heart',
    skill: 'Empatía',
    title: 'Comunicar malas noticias al equipo',
    desc: 'Hay recortes de presupuesto. Practica cómo comunicar con transparencia sin destruir la moral.',
    color: 'text-red-500',
    bg: 'bg-red-500/10',
  },
  {
    icon: 'Briefcase',
    skill: 'Confianza',
    title: 'Primera reunión con un prospecto enterprise',
    desc: 'No te conocen y son escépticos. Practica cómo generar credibilidad y confianza en los primeros 3 minutos.',
    color: 'text-purple-500',
    bg: 'bg-purple-500/10',
  },
];
