import type { LandingVideo } from '../types/landing.types';

export const LANDING_VIDEOS: Record<string, LandingVideo> = {
  queEsMaity: {
    id: 'v1',
    title: 'Qué es Maity',
    description: 'Conoce la plataforma que transforma tu comunicación',
    duration: '0:55',
    thumbnailUrl: null,
    videoUrl: 'https://youtu.be/Nf3Y_SEuhbw',
    placement: 'hero',
  },
  elProblema: {
    id: 'v2',
    title: 'El problema que nadie te dice',
    description: 'Por qué la capacitación tradicional ya no funciona',
    duration: '0:45',
    thumbnailUrl: null,
    videoUrl: null,
    placement: 'problem',
  },
  comoFunciona: {
    id: 'v3',
    title: 'Cómo funciona Maity',
    description: 'Tu escalada en 3 pasos simples',
    duration: '1:00',
    thumbnailUrl: null,
    videoUrl: null,
    placement: 'how-it-works',
  },
  laEscalada: {
    id: 'v5',
    title: 'La Escalada: tu aventura',
    description: 'Gamificación que transforma el aprendizaje',
    duration: '0:55',
    thumbnailUrl: null,
    videoUrl: null,
    placement: 'the-climb',
  },
  privacidad: {
    id: 'v8',
    title: 'Tu privacidad es sagrada',
    description: 'Así protegemos tu información',
    duration: '0:45',
    thumbnailUrl: null,
    videoUrl: null,
    placement: 'trust',
  },
  planesPrecios: {
    id: 'v12',
    title: 'Planes y precios',
    description: 'Encuentra el plan perfecto para ti',
    duration: '0:50',
    thumbnailUrl: null,
    videoUrl: null,
    placement: 'pricing',
  },
  empresa: {
    id: 'v9',
    title: 'Maity para tu empresa',
    description: 'Transforma el desarrollo de tu equipo',
    duration: '0:55',
    thumbnailUrl: null,
    videoUrl: null,
    placement: 'business-hero',
  },
};
